
import click
import numpy as np
import os
import os.path as op
import paramiko
import datetime

import file_utils

def create_ssh_client(server, port, user, password):
    client = paramiko.SSHClient()
    client.set_missing_host_key_policy(paramiko.AutoAddPolicy())
    client.connect(server, port=port, username=user, password=password)
    return client

#######################################################################
@click.command()
@click.option('--vision-asset',
              type=str,
              default=None,
              help="directory of the asset folder e.g. cube_2; encodes " + \
                "system and tosses.")
@click.option('--bundlesdf-id',
              type=str,
              default=None,
              help="what BundleSDF run ID associated with pose outputs to use.")
@click.option('--cycle-iteration',
              type=int,
              default=1,
              help="BundleSDF iteration number (can't choose 0 since that " + \
                "means use TagSLAM poses).")

def main_command(vision_asset: str, bundlesdf_id: str, cycle_iteration: int):
    assert cycle_iteration > 0, f'Invalid {cycle_iteration=}.'
    assert '_' in vision_asset, f'Invalid {vision_asset=}.'
    object = vision_asset.split('_')[0]

    start_toss = int(vision_asset.split('_')[1].split('-')[0])
    end_toss = start_toss if '-' not in vision_asset else \
        int(vision_asset.split('-')[1])
    assert start_toss <= end_toss, f'Invalid toss range: {start_toss} ' + \
            f'-{end_toss} inferred from {vision_asset=}.'

    # Decode the BundleSDF run ID.
    if bundlesdf_id[:13] != 'bundlesdf_id_':
        bundlesdf_id = f'bundlesdf_id_{bundlesdf_id}'
    print(f'Processing toss {vision_asset} from BundleSDF run ID ' + \
            f'{bundlesdf_id}.\n')

    # Get the path to the mesh file generated by BundleSDF.
    nerf_results_dir = file_utils.bundlesdf_nerf_results_dir(
        dataset=vision_asset, cycle_iteration=cycle_iteration,
        bundlesdf_id=bundlesdf_id
    )
    mesh_file = op.join(nerf_results_dir, 'mesh_cleaned.obj')

    # copy the mesh file to a remote device (which is local for the user on remote)
    # Setup SSH connection
    server = '158.130.72.130'#
    port = 22
    user = 'cnets-vision'
    password = 'dairtobelieve'
    ssh_client = create_ssh_client(server, port, user, password)

    # Copy the mesh file to local device
    local_mesh_file = mesh_file

    # Get the current date in MMDD format
    now = datetime.datetime.now()
    date_str = now.strftime('%m%d')
    remote_mesh_file_name = f'{date_str}_{vision_asset}_{bundlesdf_id[13:]}_{cycle_iteration}.obj'
    remote_directory = '/home/cnets-vision/Desktop/mesh_collection'

    remote_mesh_file = op.join(remote_directory, remote_mesh_file_name)
    print(f'Copying {local_mesh_file} to {remote_mesh_file}...')

    # Copy the mesh file to the remote device
    sftp = ssh_client.open_sftp()
    sftp.put(local_mesh_file, remote_mesh_file)
    sftp.close()


if __name__ == '__main__':
    main_command()  # pylint: disable=no-value-for-parameter
