from copy import deepcopy
import numpy as np
import math
from PIL import Image
import matplotlib.pyplot as plt
import imageio
from tqdm import tqdm
from PIL import Image
import glob
import cv2
import glob
import shutil
import os
import re
import yaml
import rospy

def load_toss_time_from_yaml(file_path, toss_type, toss_number, key):
    with open(file_path, 'r') as f:
        data = yaml.safe_load(f)
    toss_data = data['tosses'][toss_type][toss_number]
    start_time_data = toss_data[key]
    time = rospy.rostime.Time(secs=start_time_data['secs'], nsecs=start_time_data['nsecs'])
    return time

def load_field_from_yaml(file_path, toss_type, toss_number, key):
    with open(file_path, 'r') as f:
        data = yaml.safe_load(f)
    toss_data = data['tosses'][toss_type][toss_number]
    data = toss_data[key]
    return data

def load_dataset_from_yaml(file_path, toss_type):
    with open(file_path, 'r') as f:
        data = yaml.safe_load(f)
    return data['dataset'][toss_type]

def filter(real_img, sim_img):
    """
    Filter the simulated image from the real depth image.
    """
    masked_img = np.subtract(real_img, sim_img)
    return masked_img


def generate_depth_img_without_robot(depth_dir, mask_dir, filtered_depth_dir):
    """
    Filter out robot from depth image with the generated mask.
    :param str depth_dir: Directory to the original depth image from rosbag.
    :param str mask_dir: Directory to the mask generated by urdf_filter.
    :param str filtered_depth_dir: Directory to save the filtered depth image.
    """
    depth_img = np.loadtxt(depth_dir)
    # depth_img = Image.open(depth_dir)
    mask_img = Image.open(mask_dir)
    depth_array = np.array(depth_img)
    mask_array = np.array(mask_img)
    filtered_depth = deepcopy(depth_array * 1000)
    for i in range(mask_array.shape[0]):
        for j in range(mask_array.shape[1]):
            if mask_array[i][j] == 255:
                filtered_depth[i][j] = 0
    plt.imshow(filtered_depth)
    plt.colorbar()
    # plt.show()
    imageio.imwrite(filtered_depth_dir, filtered_depth.astype(np.uint16))
    return filtered_depth


def generate_rgb_image_without_robot(rgb_dir, mask_dir, filtered_rgb_dir):
    """
    Filter out robot from rgb image with the generated mask.
    :param str rgb_dir: Directory to the original rgb image from rosbag.
    :param str mask_dir: Directory to the mask generated by urdf_filter.
    :param str filtered_rgb_dir: Directory to save the filtered rgb image.
    """
    rgb_img = Image.open(rgb_dir)
    mask_img = Image.open(mask_dir)
    rgb_array = np.array(rgb_img)
    mask_array = np.array(mask_img)
    filtered_rgb = deepcopy(rgb_array)
    for i in range(mask_array.shape[0]):
        for j in range(mask_array.shape[1]):
            if mask_array[i][j] == 255:
                filtered_rgb[i][j][0] = 0
                filtered_rgb[i][j][1] = 0
                filtered_rgb[i][j][2] = 0
    # plt.imshow(filtered_rgb)
    # plt.show()
    imageio.imwrite(filtered_rgb_dir, filtered_rgb)
    return filtered_rgb


def import_data(position_file):
    """
    Load data generated from rosbag.
    """
    positions = np.loadtxt(position_file)
    print("joint position imported!")
    return positions


def write_real_depth_as_txt(start_frame, end_frame, img_dir, real_depth_dir):
    """
    Save real depth txt at once since image I/O is very slow.
    """
    loaded_arr = np.loadtxt(img_dir)
    print(loaded_arr.shape)
    load_original_arr = loaded_arr.reshape(
        loaded_arr.shape[0], loaded_arr.shape[1] // 640, 640
    )
    print("Done loading images.")
    for frame_id in tqdm(range(start_frame, end_frame + 1)):
        depth_dir = real_depth_dir % frame_id
        print("frame_id", frame_id)
        real = load_original_arr[frame_id - 1] * 0.001
        np.savetxt(depth_dir, real)


def check_empty_img(masks_dir):
    """
    Since Bundletrack loses tracking if any of the masks are empty, we need to check emptyness for masks.
    """
    empty_list = []
    nums = len([name for name in os.listdir(masks_dir)])
    for frame_id in range(1, nums+1):
        mask_file = (
            os.path.join(masks_dir, "%04i.png"% frame_id)
        )
        image = cv2.imread(mask_file)
        if np.sum(image) == 0:
            empty_list.append(frame_id)
        else:
            continue
    print(f'Empty masks: {empty_list}')
    return empty_list


def denoise(
    frame_id,
    img_dir,
    denoise_mask_dir,
    region=(10, 10),
    show=False,
):
    """
    Filter out small pieces of noise from depth images.
    """
    # img_dir = "./cube_data/depth_image_frame%04i.png" % frame_id
    img_dir = img_dir % frame_id
    # denoise_mask_dir = "/home/cnets-vision/mengti_ws/BundleTrack/Data/YCBINEOAT/contact_nets/masks/%04i.png"%frame_id
    denoise_mask_dir = os.path.join(denoise_mask_dir, "%04i.png" % frame_id)
    # Load image, convert to grayscale, Gaussian blur, Otsu's threshold
    image = cv2.imread(img_dir)
    gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
    blur = cv2.GaussianBlur(gray, (3, 3), 0)
    thresh = cv2.threshold(blur, 0, 255, cv2.THRESH_BINARY_INV + cv2.THRESH_OTSU)[1]

    # Filter using contour area and remove small noise
    cnts = cv2.findContours(thresh, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)
    cnts = cnts[0] if len(cnts) == 2 else cnts[1]
    for c in cnts:
        area = cv2.contourArea(c)
        if area < 50:
            cv2.drawContours(thresh, [c], -1, (0, 0, 0), -1)

    # Morph close and invert image
    kernel = cv2.getStructuringElement(cv2.MORPH_RECT, region)
    close = 255 - cv2.morphologyEx(thresh, cv2.MORPH_CLOSE, kernel, iterations=2)

    # cv2.imshow('thresh', thresh)
    # cv2.imshow('close', close)
    # cv2.waitKey()
    # cv2.destroyAllWindows()
    im = Image.fromarray(close)
    if im.mode != "L":
        im = im.convert("L")
    im.save(denoise_mask_dir)
    if show:
        plt.imshow(im)
        plt.show()


def render_gif():
    """
    Make pngs into a gif.
    """
    frames = []
    for frame_id in range(1, 4432):
        name = "./cube_data/screen_image_frame00000{}.png".format(frame_id)
        new_frame = Image.open(name)
        frames.append(new_frame)
    # Save into a GIF file that loops forever
    frames[0].save(
        "./png_to_gif.gif",
        format="GIF",
        append_images=frames[1:],
        save_all=True,
        duration=300,
        loop=0,
    )


def render_video():
    """
    Make pngs into a video for easy view.
    """
    fileList = []
    for frame_id in tqdm(range(1, 4432)):
        filename = "./denoise_cube_data/frame00000{}.png".format(frame_id)
        fileList.append(filename)

    writer = imageio.get_writer("new_depth.mp4", fps=20)

    for im in fileList:
        writer.append_data(imageio.imread(im))
    writer.close()

"""
Data preparation for running BundleTrack on our own RGBD data. 
"""


def copy():
    """
    For copying images from robot_filter folder to BundleTrack folder.
    """
    src_dir = "/home/cnets-vision/mengti_ws/robot_filter/depth_data"
    dst_dir = (
        "/home/cnets-vision/mengti_ws/BundleTrack/Data/YCBINEOAT/contact_nets/depth"
    )
    for jpgfile in glob.iglob(os.path.join(src_dir, "*.png")):
        shutil.copy(jpgfile, dst_dir)


def create_annotated_poses(output_dir, frame_id):
    """
    Create annotated_poses folder. First txt is the transformation matrix from camera to object.
    Others are identity matrices solely for evaluation.
    """
    filename = os.path.join(output_dir, "%04i.txt" % frame_id)
    pose = np.array([[1, 0, 0, 0], [0, 1, 0, 0], [0, 0, 1, 0], [0, 0, 0, 1]])
    np.savetxt(filename, pose)


def rename():
    """
    Currently, all data are named as frame00000{frame_id}.png. Need to rename to {frame_id}.png
    to match the required format of BundleTrack.
    Go to the directory and run rename().
    """
    for filename in os.listdir("."):
        print(filename)
        if filename.startswith("frame"):
            os.rename(filename, filename[-8:])


def removed_files(num):
    """Remove the first num frames from data folder."""
    for filename in os.listdir("."):
        name = re.findall(r"\d+", filename)[0]
        new_name = int(name)
        new_name = new_name - num
        new_filename = "%04i.txt" % new_name
        print(filename, new_filename)
        os.rename(filename, new_filename)

def replace_comma_with_space(file_path):
    """Replace every comma with a space in the specified file."""
    
    # Read the content of the file
    with open(file_path, 'r') as f:
        content = f.read()
    
    # Replace comma with space
    modified_content = content.replace(',', ' ')
    
    # Write the modified content back to the file
    with open(file_path, 'w') as f:
        f.write(modified_content)

    print(f"Replaced commas with spaces in {file_path}")

def process_directory(directory_path):
    """Apply the replace_comma_with_space function to all .txt files in the specified directory."""
    
    for root, dirs, files in os.walk(directory_path):
        for file_name in files:
            if file_name.endswith('.txt'):
                file_path = os.path.join(root, file_name)
                replace_comma_with_space(file_path)
    print('Done!')

def formulate_dataset():
    source_root = "/home/cnets-vision/mengti_ws/BundleSDF/data/"
    target_folder = "/home/cnets-vision/mengti_ws/BundleSDF/data/old_toss_10_tosses"
    subfolders = ["rgb", "depth", "masks"]
    total_folders = 10
    if not os.path.exists(target_folder):
        os.makedirs(target_folder)
    for sf in subfolders:
        target_subfolder = os.path.join(target_folder, sf)

        # Create the subfolder in the target directory
        if not os.path.exists(target_subfolder):
            os.makedirs(target_subfolder)

        current_counter = 1  # Reset counter for each subfolder type

        # Loop through each old_toss_X folder for the current subfolder type
        for i in range(1, total_folders + 1):
            source_subfolder = os.path.join(source_root, f"old_toss_{i}", sf)

            # List all files in the current subfolder
            files = sorted(os.listdir(source_subfolder))

            # Copy each file to the target subfolder and rename it
            for file in files:
                source_file_path = os.path.join(source_subfolder, file)
                target_file_name = f"{current_counter:04}.png"  # Format as 000X.png
                target_file_path = os.path.join(target_subfolder, target_file_name)

                shutil.copy2(source_file_path, target_file_path)
                # print(source_file_path, target_file_path)
                current_counter += 1
    
def main():
    # process_directory('/home/cnets-vision/mengti_ws/BundleSDF/results/ob_in_cam_projected_icp_transformed')
    formulate_dataset()
    # for frame_id in range(1, 3813):
    #     create_annotated_poses(output_dir="/home/cnets-vision/mengti_ws/BundleSDF/data/old_toss_10_tosses/annotated_poses", frame_id=frame_id)

if __name__ == "__main__":
    main()
