import math
import numpy as np
from math_utils import (
    axis_angle_to_rotation_matrix,
    quaternion_to_rotation_matrix,
    world_to_image,
)
import rosbag
from tqdm import tqdm
from matplotlib import pyplot as plt
from PIL import Image
from PIL import ImageDraw

DEPTH_ROS_TOPIC = "/camera/aligned_depth_to_color/image_raw"
JOINT_STATE_ROS_TOPIC = "/joint_states"
RGB_ROS_TOPIC = "/camera/color/image_raw"
ODOM_ROS_TOPIC = "/tagslam/odom/body_cube"

ROSBAG_NAME = "raw_10.bag"
ODOM_ROSBAG_NAME = "odom_10.bag"  # Rosbag generated by tagslam
CUBE_POSE_DIR = "/home/cnets-vision/mengti_ws/BundleTrack/Data/YCBINEOAT/contact_nets_reduced/annotated_poses/"

CUBE_LENGTH = 10.2  # cm


class Projection:
    def __init__(self, start_frame, end_frame, translation, axis_vec) -> None:
        self.start_frame = start_frame
        self.end_frame = end_frame
        self.K = np.array(
            [
                [380.2484436035156, 0, 314.2138977050781],
                [0, 379.8265380859375, 240.59800720214844],
                [0, 0, 1],
            ]
        )
        self.dict = {}
        self.extract_cube_pose(self.start_frame)
        self.extrinsic = self.setup_extrinsic(translation, axis_vec)

    def setup_extrinsic(translation, axis_vec):
        # Setup camera extrinsic
        angle = np.linalg.norm(axis_vec)
        axis = axis_vec / angle
        rotation = axis_angle_to_rotation_matrix(
            axis, angle
        )  # directions of the world-axes in camera coordinates
        rotation_prime = rotation.T  # USE THIS
        translation_prime = -rotation_prime @ translation  # USE THIS
        extrinsic = np.vstack(
            (np.hstack((rotation_prime, translation_prime)), np.array([0, 0, 0, 1]))
        )
        return extrinsic

    def world_to_image_view(self, frame_id):
        cube_vertices = self.get_vertices(frame_id)
        T, R = self.extrinsic
        points = []
        for vert in cube_vertices:
            point = world_to_image(vert, self.K, R, T)
            points.append(point)
        print(points)
        img = Image.new("L", (640, 480), 0)
        ImageDraw.Draw(img).polygon(points, outline=1, fill=1)
        # mask = np.array(img)
        plt.imshow(img)
        plt.show()

    def get_vertices(self, frame_id):
        """Get cube vertices in world coordinate. X is towards the camera,
        Y is towards the right of the robot, Z is upward.
        """
        T, R = self.dict[frame_id]
        front_left_top = np.array((CUBE_LENGTH / 2, -CUBE_LENGTH / 2, CUBE_LENGTH / 2))
        front_right_top = np.array((CUBE_LENGTH / 2, CUBE_LENGTH / 2, CUBE_LENGTH / 2))
        front_left_bottom = np.array(
            (CUBE_LENGTH / 2, -CUBE_LENGTH / 2, -CUBE_LENGTH / 2)
        )
        front_right_bottom = np.array(
            (CUBE_LENGTH / 2, CUBE_LENGTH / 2, -CUBE_LENGTH / 2)
        )

        back_left_top = np.array((-CUBE_LENGTH / 2, -CUBE_LENGTH / 2, CUBE_LENGTH / 2))
        back_right_top = np.array((-CUBE_LENGTH / 2, CUBE_LENGTH / 2, CUBE_LENGTH / 2))
        back_left_bottom = np.array(
            (-CUBE_LENGTH / 2, -CUBE_LENGTH / 2, -CUBE_LENGTH / 2)
        )
        back_right_bottom = np.array(
            (-CUBE_LENGTH / 2, CUBE_LENGTH / 2, -CUBE_LENGTH / 2)
        )

        original_vertices = np.array(
            (
                front_left_top,
                front_right_top,
                front_left_bottom,
                front_right_bottom,
                back_left_top,
                back_right_top,
                back_left_bottom,
                back_right_bottom,
            )
        )
        cube_vertices = []
        T_original, R_original = self.dict[
            1
        ]  # cube ground-truth pose in world coord for frame 1
        for vert in original_vertices:
            R_relative = R @ np.linalg.inv(R_original)
            T_relative = -R_relative @ T_original + T
            vert_ = R_relative @ vert.reshape((3, 1)) + T_relative
            cube_vertices.append(vert_)
        return cube_vertices

    def extract_cube_pose(self, start_frame):
        """Extract the pose information of the cube for the start_frame from the rosbag generated by tagslam."""
        depth_bag = rosbag.Bag(ROSBAG_NAME, "r")
        bag = rosbag.Bag(ODOM_ROSBAG_NAME, "r")
        secs = 0
        nsecs = 0
        depth_timestamps = {}
        odom_timestamps = {}
        final_odom_timestamps = {}
        for (topic, msg, ts) in depth_bag.read_messages(topics=str(DEPTH_ROS_TOPIC)):
            if msg.header.stamp.secs not in depth_timestamps.keys():
                depth_timestamps[msg.header.stamp.secs] = []
            depth_timestamps[msg.header.stamp.secs].append(msg.header.stamp.nsecs)
        print("The length of the depth_timestamps is {}".format(len(depth_timestamps)))

        for (topic, msg, ts) in bag.read_messages(topics=str(ODOM_ROS_TOPIC)):
            if msg.header.stamp.secs in depth_timestamps.keys():
                if msg.header.stamp.secs not in odom_timestamps.keys():
                    odom_timestamps[msg.header.stamp.secs] = []
                odom_timestamps[msg.header.stamp.secs].append(msg.header.stamp.nsecs)
        print("Finished processing pose_timestamps")

        for secs in tqdm(depth_timestamps.keys()):
            if secs not in final_odom_timestamps.keys():
                final_odom_timestamps[secs] = []
            for nsecs in depth_timestamps[secs]:
                closest_nsecs = math.inf
                result_nsecs = nsecs
                for pose_nsecs in odom_timestamps[secs]:
                    if abs(pose_nsecs - nsecs) < closest_nsecs:
                        result_nsecs = pose_nsecs
                        closest_nsecs = abs(pose_nsecs - nsecs)
                final_odom_timestamps[secs].append(result_nsecs)
        print(final_odom_timestamps)

        frame_id = 1
        for topic, msg, t in bag.read_messages(topics=str(ODOM_ROS_TOPIC)):
            if (
                msg.header.stamp.secs in final_odom_timestamps.keys()
                and msg.header.stamp.nsecs
                in final_odom_timestamps[msg.header.stamp.secs]
            ):
                print("Processing frame: ", frame_id)
                if frame_id == start_frame:
                    print("Saving frame ", start_frame)
                    Q = np.zeros((4, 1))
                    Q[0] = msg.pose.pose.orientation.x
                    Q[1] = msg.pose.pose.orientation.y
                    Q[2] = msg.pose.pose.orientation.z
                    Q[3] = msg.pose.pose.orientation.w
                    rotation_matrix = quaternion_to_rotation_matrix(Q)[:, :, 0]
                    P = np.zeros((3, 1))
                    P[0] = msg.pose.pose.position.x
                    P[1] = msg.pose.pose.position.y
                    P[2] = msg.pose.pose.position.z

                    self.dict[frame_id] = [P, rotation_matrix]  # position, rotation
                    # np.savetxt(ODOM_FILE_PATH+'%04i.txt'%frame_id, result) #save cube pose in camera frame
                frame_id += 1
        bag.close()
        return


if __name__ == "__main__":
    start_frame = 1
    end_frame = 1000
    proj = Projection(start_frame, end_frame)
    for frame_id in range(start_frame, end_frame):
        proj.world_to_image_view(frame_id)
        break
