### Remove the dependency of Jupyter notebook. 

import click
import numpy as np
import os
import os.path as op
import pdb
from PIL import Image
from tempfile import TemporaryDirectory
import rosbag
from selenium import webdriver
import yaml
from tqdm import tqdm

import meshcat
import meshcat.geometry as g
import meshcat.transformations as tf

import math_utils
import file_utils



# Overlay video settings.
TAGSLAM_COLOR = 0xff0000
BUNDLESDF_COLOR = 0x00ff00


class OverlayVideoGenerator:
    """Generate an overlay video to compare TagSLAM and BundleSDF poses to the
    observed RGB images."""
    def __init__(self, vision_asset: str, bundlesdf_id: str,
                 cycle_iteration: int):
        # First decode the system and start/end tosses from the provided asset
        # directory.
        assert cycle_iteration > 0, f'Invalid {cycle_iteration=}.'
        assert '_' in vision_asset, f'Invalid {vision_asset=}.'
        object = vision_asset.split('_')[0]

        start_toss = int(vision_asset.split('_')[1].split('-')[0])
        end_toss = start_toss if '-' not in vision_asset else \
            int(vision_asset.split('-')[1])
        assert start_toss <= end_toss, f'Invalid toss range: {start_toss} ' + \
                f'-{end_toss} inferred from {vision_asset=}.'

        # Decode the BundleSDF run ID.
        if bundlesdf_id[:13] != 'bundlesdf_id_':
            bundlesdf_id = f'bundlesdf_id_{bundlesdf_id}'
        
        self.vision_asset = vision_asset
        self.bundlesdf_id = bundlesdf_id
        self.cycle_iteration = cycle_iteration

        # Get the camera intrinsics and extrinsics.
        self.fx, self.fy, self.cx, self.cy = file_utils.load_camera_intrinsics()
        self.cam_trans, self.cam_axis_vec = \
            file_utils.load_camera_extrinsics(object)
        
        # Load the pose and image data.
        self._get_bundletrack_poses_in_cam()
        self._get_tagslam_poses_in_world()
        self._get_rgb_images()

        # Get the path to the mesh file generated by BundleSDF.
        nerf_results_dir = file_utils.bundlesdf_nerf_results_dir(
            dataset=vision_asset, cycle_iteration=cycle_iteration,
            bundlesdf_id=bundlesdf_id
        )
        self.mesh_file = op.join(nerf_results_dir, 'textured_mesh.obj')

        # Plan to put the output video in the BundleSDF results directory.
        bundlesdf_results_dir = file_utils.bundlesdf_run_results_dir(
            vision_asset, cycle_iteration, bundlesdf_id)
        self.output_file = op.join(bundlesdf_results_dir, 'overlay.mp4')


    def _get_bundletrack_poses_in_cam(self) -> None:
        ob_in_cam_dir = file_utils.bundlesdf_pose_dir(
            self.vision_asset, self.cycle_iteration, self.bundlesdf_id)

        frame_num = len([name for name in os.listdir(ob_in_cam_dir)])
        poses = np.zeros((frame_num, 4, 4))
        for frame_id in range(1, frame_num+1):
            pose = np.loadtxt(op.join(ob_in_cam_dir, "%04i.txt" % frame_id))
            poses[frame_id-1] = pose

        self.bundlesdf_poses_in_cam = poses

    def _get_tagslam_poses_in_world(self) -> None:
        tagslam_dir = file_utils.tagslam_pose_dir(
            self.vision_asset, check_exists=True)
        # TagSLAM data stored as [t, x, y, z, qx, qy, qz, qw].
        tagslam_data = np.loadtxt(op.join(tagslam_dir, 'tagslam.txt'))

        # Return TagSLAM poses as 4x4 homogeneous transforms.
        tagslam_poses_in_world = tagslam_data[:, 1:]
        poses = np.zeros((tagslam_poses_in_world.shape[0], 4, 4))
        for i in range(tagslam_poses_in_world.shape[0]):
            pose = tagslam_poses_in_world[i]
            poses[i] = math_utils.pos_quat_to_trans_mat(pose)

        self.tagslam_poses_in_world = poses

    def _get_rgb_images(self) -> None:
        rgb_images = []
        rgb_dir = file_utils.bundlesdf_video_rgb_dir(self.vision_asset)
        for filename in sorted(os.listdir(rgb_dir)):
            rgb_images.append(np.array(Image.open(op.join(rgb_dir, filename))))
        
        self.rgb_images = np.array(rgb_images)

        self.image_width = self.rgb_images.shape[2]
        self.image_height = self.rgb_images.shape[1]

    def _set_up_meshcat(self) -> None:
        # Can specify zmq_url="tcp://127.0.0.1:6000" argument after the first
        # run but the frame will mismatch.
        print('\nNo need to open this link: ', end='')
        vis = meshcat.Visualizer()

        ##################
        vis["tagslam_cube"].set_object(
            g.Box([0.1048, 0.1048, 0.1048]),
            g.MeshLambertMaterial(
                color=TAGSLAM_COLOR, reflectivity=0.0, transparent=0,
                opacity=.4)
        )
        vis["bundlesdf_mesh"].set_object(
            g.ObjMeshGeometry.from_file(self.mesh_file),
            g.MeshLambertMaterial(
                color=BUNDLESDF_COLOR, reflectivity=0.0, transparent=0,
                opacity=.4)
        )
        ########################
        base_url = "http://127.0.0.1"
        meshcat_url = f'{base_url}:{vis.url().split(":")[-1]}'

        ### Need x server to run. Either run locally or run remotely with x
        # forward configured.
        options = webdriver.ChromeOptions()
        options.add_argument('--headless')
        self.driver = webdriver.Chrome(options=options)

        # Set the desired window size.
        self.driver.set_window_size(self.image_width, self.image_height)
        self.driver.get(meshcat_url)

        ########################
        # Frames
        # (W) World
        # (M) Meshcat
        # (C) Camera
        # (A) TagSLAM origin
        # (B) BundleSDF origin

        # Compute T_WC, transform from world to camera.
        # TODO For some reason, need to use the inverse transform.  Maybe
        # something is misnamed.
        self.T_WC = math_utils.extrinsics_T_CW(
            self.cam_trans, self.cam_axis_vec)

        # T_MC, look along meshcat's z-axis but rotote by 180 degrees.
        self.T_MC = tf.translation_matrix([0, 0, -1]) @ \
            tf.rotation_matrix(np.pi, (0,0,1))
        self.T_MW = self.T_MC @ tf.inverse_matrix(self.T_WC)

        vis["cam"].set_transform(self.T_WC)
        vis["cam_view"].set_transform(self.T_WC)

        # The PerspectiveCamera API does not allow for vertical adjustment of
        # the center of the optical axis.  The horizontal offset is accomplished
        # via the filmOffset according to filmGauge's scale.
        fov_y = 2*np.arctan(self.image_height/(2*self.fy))*180/np.pi
        cam = g.PerspectiveCamera(
            fov=fov_y, zoom=1, aspect=self.image_width/self.image_height,
            filmGauge=self.image_width, filmOffset=self.image_width/2 - self.cx)
        vis["/Cameras/default/rotated"].set_object(cam)
        vis["/Cameras/default/rotated/<object>"].set_property(
            "position", [0,0,0])
        vis["/Cameras/default"].set_transform(self.T_MC)

        ###########################
        # view in meshcat save to images
        # Turn off background, axes, and grid.
        vis['/Background'].set_property("visible", False)
        vis['/Grid'].set_property("visible", False)
        vis['/Axes'].set_property("visible", False)

        self.vis = vis

    def make_overlay_video(self) -> None:
        print(f'Starting overlay video generation (could take minutes).')
        self._set_up_meshcat()

        with TemporaryDirectory(prefix="ros-process-") as tmpdir:
            print(f'Storing temporary files at {tmpdir}')

            # Use tqdm to show a progress bar.
            for i in tqdm(range(self.bundlesdf_poses_in_cam.shape[0])):
                im = Image.fromarray(self.rgb_images[i]).convert('RGB')

                T_WA = self.tagslam_poses_in_world[i]
                T_CB = self.bundlesdf_poses_in_cam[i]

                self.vis["tagslam_cube"].set_transform(self.T_MW @ T_WA)
                self.vis["bundlesdf_mesh"].set_transform(self.T_MC @ T_CB)

                mesh_im = self.vis.get_image()

                # Sadly meshcat's PerspectiveCamera doesn't compensate for cy,
                # only cx.  So the below manually compensates for cy.
                shift_pixels_up = round(2*(self.image_height/2 - self.cy))
                upper_buffer = np.zeros(
                    (max(0, -shift_pixels_up), self.image_width, 4)
                ).astype(np.uint8)
                lower_buffer = np.zeros(
                    (max(0, shift_pixels_up), self.image_width, 4)
                ).astype(np.uint8)

                original_data = np.array(mesh_im)
                large = np.concatenate(
                   (upper_buffer, original_data, lower_buffer), axis=0)
                start = max(0,shift_pixels_up)
                end = original_data.shape[0] + start
                small = large[start:end, :, :]
                assert original_data.shape == small.shape
                mesh_im = Image.fromarray(small).convert('RGBA')

                im.paste(mesh_im, (0,0), mask = mesh_im)
                # im.show()
                # pdb.set_trace()
                im.save(tmpdir + '/' + f'{i:07d}' + '.png', format="png")

            # Make video with ffmpeg from stored images.
            # -y means overwrite output files without asking.
            # -r {FPS} sets the frame rate.
            # -i {INPUT} specifies the input file pattern.
            # -vcodec libx264 specifies the codec as libx264.
            # -preset slow TODO not sure what this does
            # -crf 18 TODO check: specifies the quality, 0 lossless, 51 worst.
            os.system(f'ffmpeg -y -r 30 -i {tmpdir}/%07d.png -vcodec ' + \
                      f'libx264 -preset slow -crf 18 {self.output_file}')

        self.vis.delete()
        # If not exited properly, orphan chrome processes will remain active.
        self.driver.quit()
        print(f'Wrote overlay video to {self.output_file}')



#######################################################################
@click.command()
@click.option('--vision-asset',
              type=str,
              default=None,
              help="directory of the asset folder e.g. cube_2; encodes " + \
                "system and tosses.")
@click.option('--bundlesdf-id',
              type=str,
              default=None,
              help="what BundleSDF run ID associated with pose outputs to use.")
@click.option('--cycle-iteration',
              type=int,
              default=1,
              help="BundleSDF iteration number (can't choose 0 since that " + \
                "means use TagSLAM poses).")

def main_command(vision_asset: str, bundlesdf_id: str, cycle_iteration: int):
    overlay_video_generator = OverlayVideoGenerator(
        vision_asset, bundlesdf_id, cycle_iteration)
    overlay_video_generator.make_overlay_video()


if __name__ == '__main__':
    main_command()  # pylint: disable=no-value-for-parameter
