from fileinput import close
import math
import os
from tracemalloc import start
import cv2
import rosbag
import rospy
import pdb
import imageio
from PIL import Image
from cv_bridge import CvBridge
import numpy as np
import matplotlib.pyplot as plt
from tqdm import tqdm
import tf
from math_utils import world_to_camera
from dataclasses import dataclass
from nav_msgs.msg import Odometry
from scipy.spatial.transform import Rotation as R

DEPTH_ROS_TOPIC = "/camera/aligned_depth_to_color/image_raw"
JOINT_STATE_ROS_TOPIC = "/joint_states"
RGB_ROS_TOPIC = "/camera/color/image_raw"
ODOM_ROS_TOPIC = "/tagslam/odom/body_box"

IMAGE_FILE_PATH = "./texts/images.txt"
POSITION_FILE_PATH = "./texts/joint_position.txt"
ODOM_FILE_PATH = "/home/cnets-vision/mengti_ws/BundleTrack/Data/YCBINEOAT/contact_nets/annotated_poses/"
GT_ODOM_FILE_PATH = "/home/cnets-vision/mengti_ws/robot_filter/tagslam_poses/"
TIMESTAMP_FILE_PATH = (
    "/home/cnets-vision/mengti_ws/robot_filter/tagslam_poses/timestamps.txt"
)

DEPTH_OUTPUT_DIR = "./depth_data"
BUNDLETRACK_DEPTH_DIR = (
    "/home/cnets-vision/mengti_ws/BundleTrack/Data/YCBINEOAT/contact_nets/depth"
)
BUNDLETRACK_RGB_DIR = (
    "/home/cnets-vision/mengti_ws/BundleTrack/Data/YCBINEOAT/contact_nets/rgb"
)
RGB_OUTPUT_DIR = "./rgb_data"
ROSBAG_NAME = "raw_19.bag"
ODOM_ROSBAG_NAME = "odom_19.bag"  # Rosbag generated by tagslam


def getDictLen(dict):
    length = 0
    for k in dict.keys():
        length += len(dict[k])
    return length


def bag_to_rgb_images(bag_file, image_topic, image_dir, start_time, end_time):
    """Extract a folder of RGB images from a rosbag."""
    print(
        "Extract images from %s on topic %s into %s"
        % (bag_file, image_topic, image_dir)
    )

    bag = rosbag.Bag(bag_file, "r")
    bridge = CvBridge()
    filename = 1
    for topic, msg, t in bag.read_messages(topics=[image_topic]):
        if start_time and end_time:
            if msg.header.stamp < start_time:
                continue
            if msg.header.stamp >= end_time:
                break
        cv_img = bridge.imgmsg_to_cv2(msg, desired_encoding="passthrough")
        cv2.imwrite(os.path.join(image_dir, "%04i.png" % filename), cv_img)
        filename += 1
        # im = Image.fromarray(depth_array)
        # if im.mode != 'RGB':
        #     im = im.convert('RGB')

        print("Wrote image %i" % filename)
    bag.close()
    return


def bag_to_depth_images(
    rosbag_name,
    depth_ros_topic,
    depth_dir,
    start_time,
    end_time,
    img_dir,
    bundletrack_depth_dir,
):
    """Extract a folder of depth images from a rosbag."""
    print(
        "Extract images from %s on topic %s into %s"
        % (rosbag_name, depth_ros_topic, depth_dir)
    )

    bag = rosbag.Bag(rosbag_name, "r")
    bridge = CvBridge()
    arr = []
    filename = 1
    for topic, msg, t in bag.read_messages(topics=[depth_ros_topic]):
        if start_time and end_time:
            if msg.header.stamp < start_time:
                continue
            if msg.header.stamp >= end_time:
                break
        cv_img = bridge.imgmsg_to_cv2(msg, desired_encoding="16UC1")  # this is uint16
        # depth_array_mm = np.array(cv_img, dtype=np.float32)  # true depth in millimeters
        # depth_array = depth_array_mm * 0.001  # convert millimeters to meters

        arr.append(np.uint16(cv_img))
        imageio.imwrite(
            os.path.join(bundletrack_depth_dir, "%04i.png" % filename),
            np.uint16(cv_img),
        )
        # cv_img_meter_scale = cv_img * 0.001
        imageio.imwrite(
            os.path.join(depth_dir, "%04i.png" % filename), np.uint16(cv_img)
        )
        loaded_img = imageio.imread(os.path.join(depth_dir, "%04i.png" % filename))
        print("Wrote image %04i.png in the format %s" % (filename, loaded_img.dtype))
        filename += 1
    arr = np.array(arr)
    arr_reshaped = arr.reshape(arr.shape[0], -1)
    np.savetxt(img_dir, arr_reshaped)
    print("Depth images saved!")
    bag.close()
    return


def bag_to_pose(
    bagfile, pose_topic, outfile_position, outfile_velocity, start_frame, end_frame
):
    """
    Write /joint_states to a file
    """
    # To make sure we read images and poses approximately at the same rate
    offset = 32
    n = start_frame
    position = []
    velocity = []
    with rosbag.Bag(bagfile, "r") as bag:
        prev = start_frame
        for (topic, msg, ts) in bag.read_messages(topics=str(pose_topic)):
            if msg.header.seq < n:
                continue
            if msg.header.seq - prev <= offset:
                continue
            prev = msg.header.seq
            print("recording frame: ", msg.header.seq)
            reordered_position = [0] * len(msg.position)
            reordered_position[:7] = msg.position[2:]
            reordered_position[-2:] = msg.position[:2]
            reordered_velocity = [0] * len(msg.velocity)
            reordered_velocity[:7] = msg.velocity[2:]
            reordered_velocity[-2:] = msg.velocity[:2]

            position.append(reordered_position)
            velocity.append(reordered_velocity)
            n += 1
            if n == end_frame:
                break
        position = np.array(position)
        velocity = np.array(velocity)
        np.savetxt(outfile_position, position)
        np.savetxt(outfile_velocity, velocity)
        # check the shapes
        loaded_position = np.loadtxt(outfile_position)
        loaded_velocity = np.loadtxt(outfile_velocity)
        print("shape of position: ", position.shape)
        print("shape of loaded_position: ", loaded_position.shape)
        print("shape of velocity: ", velocity.shape)
        print("shape of loaded_velocity: ", loaded_velocity.shape)
    print(
        "wrote "
        + str(n)
        + " imu messages to the file: "
        + outfile_position
        + " and "
        + outfile_velocity
    )


def extract_poses_with_timestamps(
    bagfile,
    depth_topic,
    rgb_topic,
    pose_topic,
    outfile_position,
    outfile_rgb,
    start_time,
    end_time,
    bundletrack_rgb_dir,
):
    """
    Extract poses from rosbag according to matching timestamps between depth topic and pose topic.
    """
    bridge = CvBridge()
    depth_timestamps = {}  # depth topic
    pose_timestamps = {}  # pose topic
    final_pose_timestamps = {}  # timestamps to extract for pose topic
    rgb_timestamps = {}  # rgb topic
    final_rgb_timestamps = {}  # timestamps to extract for rgb topic
    position = []
    n = 0
    m = 0
    rgb_filename = 1
    with rosbag.Bag(bagfile, "r") as bag:
        for (topic, msg, ts) in bag.read_messages(topics=str(depth_topic)):
            print("processing ", ts)
            if msg.header.stamp.secs not in depth_timestamps.keys():
                depth_timestamps[msg.header.stamp.secs] = []
            depth_timestamps[msg.header.stamp.secs].append(msg.header.stamp.nsecs)
        print("The length of the depth_timestamps is {}".format(len(depth_timestamps)))

        # Processing pose topic
        # Get the hashmap for pose topic
        for (topic, msg, ts) in bag.read_messages(topics=str(pose_topic)):
            if msg.header.stamp.secs in depth_timestamps.keys():
                if msg.header.stamp.secs not in pose_timestamps.keys():
                    pose_timestamps[msg.header.stamp.secs] = []
                pose_timestamps[msg.header.stamp.secs].append(msg.header.stamp.nsecs)
        print("Finished processing pose_timestamps")

        for secs in tqdm(depth_timestamps.keys()):
            if secs not in final_pose_timestamps.keys():
                final_pose_timestamps[secs] = []
            for nsecs in depth_timestamps[secs]:
                closest_nsecs = math.inf
                result_nsecs = nsecs
                for pose_nsecs in pose_timestamps[secs]:
                    if abs(pose_nsecs - nsecs) < closest_nsecs:
                        result_nsecs = pose_nsecs
                        closest_nsecs = abs(pose_nsecs - nsecs)
                final_pose_timestamps[secs].append(result_nsecs)
        print("Finished recording final_pose_timestamps")

        # Extract poses with the timestamps we want to keep
        for (topic, msg, ts) in bag.read_messages(topics=str(pose_topic)):
            if (
                msg.header.stamp.secs in final_pose_timestamps.keys()
                and msg.header.stamp.nsecs
                in final_pose_timestamps[msg.header.stamp.secs]
            ):
                n += 1
                if start_time and end_time:
                    if msg.header.stamp < start_time:
                        continue
                    if msg.header.stamp >= end_time:
                        break
                reordered_position = [0] * len(msg.position)
                reordered_position[:7] = msg.position[2:]
                reordered_position[-2:] = msg.position[:2]
                position.append(reordered_position)

                print("Processing ", n, "th frame.")
        position = np.array(position)
        np.savetxt(outfile_position, position)
        # check the shapes
        loaded_position = np.loadtxt(outfile_position)
        print("shape of position: ", position.shape)
        print("shape of loaded_position: ", loaded_position.shape)

        # Processing RGB topic
        for (topic, msg, ts) in bag.read_messages(topics=str(rgb_topic)):
            if msg.header.stamp.secs in depth_timestamps.keys():
                if msg.header.stamp.secs not in rgb_timestamps.keys():
                    rgb_timestamps[msg.header.stamp.secs] = []
                rgb_timestamps[msg.header.stamp.secs].append(msg.header.stamp.nsecs)
        print("Finished processing rgb_timestamps")

        for secs in tqdm(depth_timestamps.keys()):
            if secs not in final_rgb_timestamps.keys():
                final_rgb_timestamps[secs] = []
            for nsecs in depth_timestamps[secs]:
                closest_nsecs = math.inf
                result_nsecs = nsecs
                for pose_nsecs in rgb_timestamps[secs]:
                    if abs(pose_nsecs - nsecs) < closest_nsecs:
                        result_nsecs = pose_nsecs
                        closest_nsecs = abs(pose_nsecs - nsecs)
                final_rgb_timestamps[secs].append(result_nsecs)
        print("Finished recording final_rgb_timestamps")

        for (topic, msg, ts) in bag.read_messages(topics=str(rgb_topic)):
            if (
                msg.header.stamp.secs in final_rgb_timestamps.keys()
                and msg.header.stamp.nsecs
                in final_rgb_timestamps[msg.header.stamp.secs]
            ):
                m += 1
                if start_time and end_time:
                    if msg.header.stamp < start_time:
                        continue
                    if msg.header.stamp >= end_time:
                        break
                cv_img = bridge.imgmsg_to_cv2(msg, desired_encoding="passthrough")
                cv2.imwrite(
                    os.path.join(outfile_rgb, "%04i.png" % rgb_filename), cv_img
                )
                cv2.imwrite(
                    os.path.join(bundletrack_rgb_dir, "%04i.png" % rgb_filename), cv_img
                )
                rgb_filename += 1
                print("Wrote image %i" % m)

    print("wrote " + str(n) + " imu messages to the file: " + outfile_position)


def extract_cube_pose(
    start_time,
    end_time,
    bagfile,
    odom_bagfile,
    odom_topic,
    odom_file_path,
    cam_translation,
    cam_axis_vec,
):
    """
    Extract the pose information of the cube for the start_frame from the rosbag generated by tagslam.
    """
    depth_bag = rosbag.Bag(bagfile, "r")
    odom_bag = rosbag.Bag(odom_bagfile, "r")
    secs = 0
    nsecs = 0
    depth_timestamps = {}
    odom_timestamps = {}
    final_odom_timestamps = {}
    print("Reading depth bag: %s and odom bag: %s" % (bagfile, odom_bagfile))
    for (topic, msg, ts) in depth_bag.read_messages(topics=str(DEPTH_ROS_TOPIC)):
        if start_time and end_time:
            if msg.header.stamp < start_time:
                continue
            if msg.header.stamp >= end_time:
                break
        if msg.header.stamp.secs not in depth_timestamps.keys():
            depth_timestamps[msg.header.stamp.secs] = []
        depth_timestamps[msg.header.stamp.secs].append(msg.header.stamp.nsecs)
    print("The length of the depth_timestamps is {}".format(len(depth_timestamps)))

    for (topic, msg, ts) in odom_bag.read_messages(topics=str(odom_topic)):
        if msg.header.stamp.secs in depth_timestamps.keys():
            if msg.header.stamp.secs not in odom_timestamps.keys():
                odom_timestamps[msg.header.stamp.secs] = []
            odom_timestamps[msg.header.stamp.secs].append(msg.header.stamp.nsecs)
    print("The length of odom_timestamps is {}".format(len(odom_timestamps)))
    for secs in tqdm(depth_timestamps.keys()):
        if secs not in final_odom_timestamps.keys():
            final_odom_timestamps[secs] = []
        for nsecs in depth_timestamps[secs]:
            closest_nsecs = math.inf
            result_nsecs = nsecs
            if secs not in odom_timestamps.keys():
                continue
            for pose_nsecs in odom_timestamps[secs]:
                if abs(pose_nsecs - nsecs) < closest_nsecs:
                    result_nsecs = pose_nsecs
                    closest_nsecs = abs(pose_nsecs - nsecs)
            final_odom_timestamps[secs].append(result_nsecs)
    frame_id = 0
    for topic, msg, t in odom_bag.read_messages(topics=str(odom_topic)):
        if (
            msg.header.stamp.secs in final_odom_timestamps.keys()
            and msg.header.stamp.nsecs in final_odom_timestamps[msg.header.stamp.secs]
        ):
            if start_time and end_time:
                if msg.header.stamp < start_time:
                    continue
                if msg.header.stamp >= end_time:
                    break
            print("Processing frame: ", frame_id)
            Q = np.zeros((4,))
            Q[0] = msg.pose.pose.orientation.x
            Q[1] = msg.pose.pose.orientation.y
            Q[2] = msg.pose.pose.orientation.z
            Q[3] = msg.pose.pose.orientation.w
            rotation_matrix = R.from_quat(Q).as_matrix()
            position = msg.pose.pose.position
            translation = np.array([[position.x], [position.y], [position.z]])
            result = np.vstack(
                (np.hstack((rotation_matrix, translation)), np.array([0, 0, 0, 1]))
            )
            result = world_to_camera(result, cam_translation, cam_axis_vec)
            np.savetxt(
                os.path.join(odom_file_path, "%04i.txt" % frame_id), result
            )  # save cube pose in camera frame
            print(
                "Saving the timestamp at: ",
                msg.header.stamp.secs,
                msg.header.stamp.nsecs,
            )
            break  # only need pose for the first frame
    depth_bag.close()
    odom_bag.close()
    return


def extract_gt_poses_from_tagslam(
    start_time,
    end_time,
    depth_bag_file,
    odom_bag_file,
    depth_topic,
    odom_topic,
    output_dir,
):
    """
    Extract the pose information of the cube from tagslam to testify the results of BuddleTrack. Assuming odometry is complete.
    """
    depth_bag = rosbag.Bag(depth_bag_file, "r")
    odom_bag = rosbag.Bag(odom_bag_file, "r")
    depth_timestamps = {}
    odom_timestamps = {}
    final_odom_timestamps = {}  # timestamps to extract for pose topic
    for (topic, msg, ts) in depth_bag.read_messages(topics=str(depth_topic)):
        if start_time and end_time:
            if msg.header.stamp < start_time:
                continue
            if msg.header.stamp >= end_time:
                break
        if msg.header.stamp.secs not in depth_timestamps.keys():
            depth_timestamps[msg.header.stamp.secs] = []
        depth_timestamps[msg.header.stamp.secs].append(msg.header.stamp.nsecs)
    print(
        "The length of the depth_timestamps is {}".format(getDictLen(depth_timestamps))
    )

    # Record the timestamps for calculating angular/linear velocities later
    # frame_id = 1
    # final_timestamps = []
    # for sec in depth_timestamps.keys():
    #     for nsec in depth_timestamps[sec]:
    #         final_timestamps.append(np.array([frame_id, sec, nsec]))
    #         frame_id+=1
    # arr = np.array(final_timestamps)
    # np.savetxt(TIMESTAMP_FILE_PATH, arr)

    # Processing tagslam bag to get timestamps that matches the depth topic
    for (topic, msg, ts) in odom_bag.read_messages(topics=str(odom_topic)):
        if msg.header.stamp.secs in depth_timestamps.keys():
            if msg.header.stamp.secs not in odom_timestamps.keys():
                odom_timestamps[msg.header.stamp.secs] = []
            odom_timestamps[msg.header.stamp.secs].append(msg.header.stamp.nsecs)
    print("The length of the odom_timestamps is {}".format(getDictLen(odom_timestamps)))
    id = 1
    for secs in tqdm(depth_timestamps.keys()):
        if secs not in final_odom_timestamps.keys():
            final_odom_timestamps[secs] = []
        for nsecs in depth_timestamps[secs]:
            closest_nsecs = math.inf
            result_nsecs = nsecs
            # if secs not in odom_timestamps.keys():
            #     continue
            for odom_nsecs in odom_timestamps[secs]:
                if abs(odom_nsecs - nsecs) < closest_nsecs:
                    # print("Updating ...")
                    result_nsecs = odom_nsecs
                    closest_nsecs = abs(odom_nsecs - nsecs)
            if result_nsecs in final_odom_timestamps[secs]:
                print("Skipping...", id)
                id += 1
                continue
            final_odom_timestamps[secs].append(result_nsecs)
            id += 1
    print(
        "The length of the final_odom_timestamps is {}".format(
            getDictLen(final_odom_timestamps)
        )
    )
    frame_id = 1
    for (topic, msg, ts) in odom_bag.read_messages(topics=str(odom_topic)):
        if msg.header.stamp.secs in final_odom_timestamps.keys():
            if msg.header.stamp.nsecs in final_odom_timestamps[msg.header.stamp.secs]:
                Q = np.zeros((4,))
                Q[0] = msg.pose.pose.orientation.x
                Q[1] = msg.pose.pose.orientation.y
                Q[2] = msg.pose.pose.orientation.z
                Q[3] = msg.pose.pose.orientation.w
                rotation_matrix = R.from_quat(Q).as_matrix()
                position = msg.pose.pose.position
                translation = np.array([[position.x], [position.y], [position.z]])
                result = np.vstack(
                    (np.hstack((rotation_matrix, translation)), np.array([0, 0, 0, 1]))
                )
                np.savetxt(output_dir + "%04i.txt" % frame_id, result)
                frame_id += 1
    print("Recorded %i frames" % frame_id)
    depth_bag.close()
    odom_bag.close()
    return


def extract_gt_poses_from_tagslam_with_quat(
    start_time,
    end_time,
    depth_bag_file,
    odom_bag_file,
    depth_topic,
    odom_topic,
    output_dir,
):
    """
    Extract the pose information of the cube from tagslam to testify the results of BuddleTrack. Assuming odometry is complete.
    """
    depth_bag = rosbag.Bag(depth_bag_file, "r")
    odom_bag = rosbag.Bag(odom_bag_file, "r")
    depth_timestamps = {}
    odom_timestamps = {}
    final_odom_timestamps = {}  # timestamps to extract for pose topic
    for (topic, msg, ts) in depth_bag.read_messages(topics=str(depth_topic)):
        if start_time and end_time:
            if msg.header.stamp < start_time:
                continue
            if msg.header.stamp >= end_time:
                break
        if msg.header.stamp.secs not in depth_timestamps.keys():
            depth_timestamps[msg.header.stamp.secs] = []
        depth_timestamps[msg.header.stamp.secs].append(msg.header.stamp.nsecs)
    print(
        "The length of the depth_timestamps is {}".format(getDictLen(depth_timestamps))
    )

    # Record the timestamps for calculating angular/linear velocities later
    # frame_id = 1
    # final_timestamps = []
    # for sec in depth_timestamps.keys():
    #     for nsec in depth_timestamps[sec]:
    #         final_timestamps.append(np.array([frame_id, sec, nsec]))
    #         frame_id+=1
    # arr = np.array(final_timestamps)
    # np.savetxt(TIMESTAMP_FILE_PATH, arr)

    # Processing tagslam bag to get timestamps that matches the depth topic
    for (topic, msg, ts) in odom_bag.read_messages(topics=str(odom_topic)):
        if msg.header.stamp.secs in depth_timestamps.keys():
            if msg.header.stamp.secs not in odom_timestamps.keys():
                odom_timestamps[msg.header.stamp.secs] = []
            odom_timestamps[msg.header.stamp.secs].append(msg.header.stamp.nsecs)
    print("The length of the odom_timestamps is {}".format(getDictLen(odom_timestamps)))
    id = 1
    for secs in tqdm(depth_timestamps.keys()):
        if secs not in final_odom_timestamps.keys():
            final_odom_timestamps[secs] = []
        for nsecs in depth_timestamps[secs]:
            closest_nsecs = math.inf
            result_nsecs = nsecs
            # if secs not in odom_timestamps.keys():
            #     continue
            for odom_nsecs in odom_timestamps[secs]:
                if abs(odom_nsecs - nsecs) < closest_nsecs:
                    # print("Updating ...")
                    result_nsecs = odom_nsecs
                    closest_nsecs = abs(odom_nsecs - nsecs)
            if result_nsecs in final_odom_timestamps[secs]:
                print("Skipping...", id)
                id += 1
                continue
            final_odom_timestamps[secs].append(result_nsecs)
            id += 1
    print(
        "The length of the final_odom_timestamps is {}".format(
            getDictLen(final_odom_timestamps)
        )
    )
    frame_id = 1
    for (topic, msg, ts) in odom_bag.read_messages(topics=str(odom_topic)):
        if msg.header.stamp.secs in final_odom_timestamps.keys():
            if msg.header.stamp.nsecs in final_odom_timestamps[msg.header.stamp.secs]:
                position = msg.pose.pose.position
                Q = np.zeros((7, 1))
                Q[0] = position.x
                Q[1] = position.y
                Q[2] = position.z
                Q[3] = msg.pose.pose.orientation.x
                Q[4] = msg.pose.pose.orientation.y
                Q[5] = msg.pose.pose.orientation.z
                Q[6] = msg.pose.pose.orientation.w
                np.savetxt(output_dir + "%04i.txt" % frame_id, Q)
                frame_id += 1
    print("Recorded %i frames" % frame_id)
    depth_bag.close()
    odom_bag.close()
    return


@dataclass
class BagInfo:
    rostime: rospy.rostime.Time
    msg: Odometry()


def extract_gt_poses_from_tagslam_with_missing_frames(
    start_time,
    end_time,
    depth_bag_file,
    odom_bag_file,
    depth_topic,
    odom_topic,
    output_dir,
    write=True,
):
    """Extract the pose information of the cube from tagslam to testify the results of BuddleTrack.
    Assuming odometry is incomplete.
    """
    depth_bag = rosbag.Bag(depth_bag_file, "r")
    odom_bag = rosbag.Bag(odom_bag_file, "r")
    depth_timestamps = {}
    global odom_timestamps_
    odom_timestamps_ = {}
    gt_timestamps = []
    frame_id = 1
    record = 0
    for (topic, msg, ts) in odom_bag.read_messages(topics=str(odom_topic)):
        if start_time and end_time:
            # if msg.header.stamp < start_time:
            #     continue
            # if msg.header.stamp >= end_time:
            #     break
            if frame_id < start_time:
                continue
            if frame_id > end_time:
                break
        if msg.header.stamp.secs not in odom_timestamps_.keys():
            odom_timestamps_[msg.header.stamp.secs] = []
        odom_timestamps_[msg.header.stamp.secs].append(
            BagInfo(msg.header.stamp, msg.pose.pose)
        )
        frame_id += 1
    frame_id = 1
    for (topic, msg, ts) in depth_bag.read_messages(topics=str(depth_topic)):
        if start_time and end_time:
            # if msg.header.stamp < start_time:
            #     continue
            # if msg.header.stamp >= end_time:
            #     break
            if frame_id < start_time:
                continue
            if frame_id > end_time:
                break
        nearest_neighbor = find_nearest_neighbor(msg.header.stamp)
        if nearest_neighbor != None:
            Q = np.zeros((4,))
            Q[0] = msg.pose.pose.orientation.x
            Q[1] = msg.pose.pose.orientation.y
            Q[2] = msg.pose.pose.orientation.z
            Q[3] = msg.pose.pose.orientation.w
            rotation_matrix = R.from_quat(Q).as_matrix()
            position = nearest_neighbor.position
            translation = np.array([[position.x], [position.y], [position.z]])
            result = np.vstack(
                (np.hstack((rotation_matrix, translation)), np.array([0, 0, 0, 1]))
            )
            if write:
                np.savetxt(output_dir + "%04i.txt" % frame_id, result)
            frame_id += 1
            record += 1
            gt_timestamps.append(msg.header.stamp.to_nsec())
        # else:
        #     np.savetxt(output_dir + "%04i.txt" % frame_id, np.identity(4))
        #     frame_id += 1
    print(f"record is {record}")
    depth_bag.close()
    odom_bag.close()
    return gt_timestamps


def find_nearest_neighbor(depth_timestamp):
    closest_diff = np.inf
    closest_nsecs = None
    closest_secs = None
    msg = None
    for i, odom_secs in enumerate(odom_timestamps_):
        for odom in odom_timestamps_[odom_secs]:
            if odom_secs == depth_timestamp.secs:
                diff = abs(depth_timestamp.nsecs - odom.rostime.nsecs)
                if diff < closest_diff:
                    closest_diff = diff
                    closest_nsecs = odom.rostime.nsecs
                    closest_secs = odom_secs
                    msg = odom.msg
    if closest_nsecs != None:
        my_list = odom_timestamps_[closest_secs]
        element_to_remove = BagInfo(
            rospy.rostime.Time(closest_secs, closest_nsecs), msg
        )
        odom_timestamps_[closest_secs] = [
            item for item in my_list if item != element_to_remove
        ]
        # print('Element removed!')
    return msg


def extract_time_versus_poses(
    start_time,
    end_time,
    depth_bag_file,
    odom_bag_file,
    depth_topic,
    odom_topic,
    output_dir,
    save=False,
    time_offset=0.0,
):
    depth_bag = rosbag.Bag(depth_bag_file, "r")
    odom_bag = rosbag.Bag(odom_bag_file, "r")
    bundletrack_time = []
    odom_time = []
    frame = 1
    tagslam_poses = []
    for (topic, msg, ts) in depth_bag.read_messages(topics=str(depth_topic)):
        if start_time and end_time:
            if msg.header.stamp < start_time:
                continue
            if msg.header.stamp >= end_time:
                break
        btime = msg.header.stamp.secs + msg.header.stamp.nsecs * 1e-9
        bundletrack_time.append(btime)
        frame+=1
    print("The length of the bundletrack_time is {}".format(len(bundletrack_time)))

    frame_id = 1
    for (topic, msg, ts) in odom_bag.read_messages(topics=str(odom_topic)):
        if start_time and end_time:
            if msg.header.stamp+rospy.Duration(time_offset) < start_time:
                continue
            if msg.header.stamp+rospy.Duration(time_offset) >= end_time:
                break
        shifted_timestamp = msg.header.stamp+rospy.Duration(time_offset)
        gtime = shifted_timestamp.secs + shifted_timestamp.nsecs * 1e-9
        odom_time.append(gtime)
        
        Q = np.zeros((7,))
        position = msg.pose.pose.position
        Q[0] = position.x
        Q[1] = position.y
        Q[2] = position.z
        Q[3] = msg.pose.pose.orientation.x
        Q[4] = msg.pose.pose.orientation.y
        Q[5] = msg.pose.pose.orientation.z
        Q[6] = msg.pose.pose.orientation.w
        tagslam_poses.append(Q)
        frame_id += 1
    tagslam_poses = np.array(tagslam_poses).T
    bundletrack_time = np.expand_dims(bundletrack_time,axis=0)
    odom_time = np.expand_dims(odom_time,axis=0)
    data = np.concatenate((odom_time, tagslam_poses), axis=0)
    data = data.T #N, 9
    if save:
        np.savetxt(output_dir + 'tagslam.txt', data)
        print(output_dir + 'tagslam.txt saved!')
    depth_bag.close()
    odom_bag.close()
    return bundletrack_time.reshape(-1,)


def extract_toss_duration(bagfile, topic, threshold):
    """
    Get start and end timestamps of tosses. New toss is defined as remainig static for longer than 3 seconds.

    :param threshold: rospy.Duration in second
    """
    bag = rosbag.Bag(bagfile, "r")
    prev_msg = None  # Pose of object in previous frame
    result_times = {}
    toss_idx = 1
    for (topic, msg, ts) in bag.read_messages(topics=str(topic)):

        def get_duration(msg1, msg2):
            # Assuming msg2 is after msg1
            diff = abs(msg2.header.stamp.to_nsec() - msg1.header.stamp.to_nsec())
            return diff

        def isclose(n1, n2, eps=0.01):
            return all(x <= eps for x in abs(n1 - n2))

        def is_static(msg1, msg2):
            P1, P2 = np.zeros((3,)), np.zeros((3,))
            P1[0] = msg1.pose.pose.position.x
            P1[1] = msg1.pose.pose.position.y
            P1[2] = msg1.pose.pose.position.z

            P2[0] = msg2.pose.pose.position.x
            P2[1] = msg2.pose.pose.position.y
            P2[2] = msg2.pose.pose.position.z
            # print(P1, P2)
            pos_static = isclose(P1, P2)
            Q1, Q2 = np.zeros((4,)), np.zeros((4,))
            Q1[0] = msg1.pose.pose.orientation.x
            Q1[1] = msg1.pose.pose.orientation.y
            Q1[2] = msg1.pose.pose.orientation.z
            Q1[3] = msg1.pose.pose.orientation.w

            Q2[0] = msg2.pose.pose.orientation.x
            Q2[1] = msg2.pose.pose.orientation.y
            Q2[2] = msg2.pose.pose.orientation.z
            Q2[3] = msg2.pose.pose.orientation.w
            # print(Q1, Q2)
            ori_static = isclose(Q1, Q2)
            return pos_static and ori_static

        if prev_msg != None and is_static(prev_msg, msg):
            # print(get_duration(prev_msg, msg))
            if get_duration(prev_msg, msg) >= threshold.to_nsec():
                prev_msg = msg
                if toss_idx not in result_times:
                    result_times[toss_idx] = []
                result_times[toss_idx].append(prev_msg.header.stamp)
                result_times[toss_idx].append(msg.header.stamp)
                toss_idx += 1
        else:
            prev_msg = msg

    bag.close()
    print(result_times)
    return result_times

def extract_timestamps(bagfile, topic, start_time, end_time):
    """
    Extract timestamps from rosbag in specified range.
    """
    timestamps = []
    bag = rosbag.Bag(bagfile, "r")
    for (topic, msg, ts) in bag.read_messages(topics=str(topic)):
        if start_time <= msg.header.stamp < end_time:
            timestamps.append(msg.header.stamp)
    return timestamps

if __name__ == "__main__":
    extract_toss_duration(ODOM_ROSBAG_NAME, ODOM_ROS_TOPIC, rospy.Duration(3))
# bag_to_depth_images(701)
# extract_poses_with_timestamps(ROSBAG_NAME, DEPTH_ROS_TOPIC, RGB_ROS_TOPIC, JOINT_STATE_ROS_TOPIC, POSITION_FILE_PATH, VELOCITY_FILE_PATH, RGB_OUTPUT_DIR, 1)
# extract_cube_pose(701)
# extract_gt_poses_from_tagslam(ROSBAG_NAME, ODOM_ROSBAG_NAME, DEPTH_ROS_TOPIC, ODOM_ROS_TOPIC, GT_ODOM_FILE_PATH)
