from fileinput import close
import math
import os
import cv2
import rosbag
import rospy
from PIL import Image
from cv_bridge import CvBridge
import numpy as np
import matplotlib.pyplot as plt
from tqdm import tqdm

from math_utils import quaternion_to_rotation_matrix, world_to_camera

DEPTH_ROS_TOPIC = "/camera/aligned_depth_to_color/image_raw"
JOINT_STATE_ROS_TOPIC = "/joint_states"
RGB_ROS_TOPIC = "/camera/color/image_raw"
ODOM_ROS_TOPIC = "/tagslam/odom/body_cube"

IMAGE_FILE_PATH = "./depth_data/images.txt"
POSITION_FILE_PATH = "./depth_data/joint_position.txt"
VELOCITY_FILE_PATH = "./depth_data/joint_velocity.txt"
ODOM_FILE_PATH = "/home/cnets-vision/mengti_ws/BundleTrack/Data/YCBINEOAT/contact_nets_reduced/annotated_poses/"
GT_ODOM_FILE_PATH = "/home/cnets-vision/mengti_ws/robot_filter/tagslam_poses/"
TIMESTAMP_FILE_PATH = "/home/cnets-vision/mengti_ws/robot_filter/tagslam_poses/timestamps.txt"

DEPTH_OUTPUT_DIR = "./depth_data"
RGB_OUTPUT_DIR = "./rgb_data"
ROSBAG_NAME = "raw_10.bag"
ODOM_ROSBAG_NAME = "odom_10.bag" #Rosbag generated by tagslam

def bag_to_rgb_images(bag_file, image_topic, start_frame):
    """Extract a folder of RGB images from a rosbag.
    """
    print("Extract images from %s on topic %s into %s" % (bag_file,
                                                          image_topic, 
                                                          RGB_OUTPUT_DIR))

    bag = rosbag.Bag(bag_file, "r")
    bridge = CvBridge()
    filename = 1
    count = 0
    for topic, msg, t in bag.read_messages(topics=[image_topic]):
        count += 1
        if count < start_frame:
            continue
        cv_img = bridge.imgmsg_to_cv2(msg, desired_encoding="passthrough")
        cv2.imwrite(os.path.join(RGB_OUTPUT_DIR, "%04i.png" % filename), cv_img)
        filename+=1
        # im = Image.fromarray(depth_array)
        # if im.mode != 'RGB':
        #     im = im.convert('RGB')
        
        print("Wrote image %i" % count)

        # Rosbag is too large, we only keep the first 10 images
        # if count == end_frame:
        #     break 
    bag.close()
    return

def bag_to_depth_images(start_frame):
    """Extract a folder of depth images from a rosbag.
    """
    print("Extract images from %s on topic %s into %s" % (ROSBAG_NAME,
                                                          DEPTH_ROS_TOPIC, 
                                                          DEPTH_OUTPUT_DIR))

    bag = rosbag.Bag(ROSBAG_NAME, "r")
    bridge = CvBridge()
    count = 0
    arr = []
    filename = 1
    for topic, msg, t in bag.read_messages(topics=[DEPTH_ROS_TOPIC]):
        count += 1
        if count < start_frame:
            continue
        cv_img = bridge.imgmsg_to_cv2(msg, desired_encoding="passthrough")
        depth_array = np.array(cv_img)*0.001
        
        # This is temporarily not being used
        # cv2.imwrite(os.path.join(output_dir, "frame%06i.png" % count), cv_img)
        arr.append(depth_array)

        im = Image.fromarray(depth_array)
        im = im.convert('L')
        im.save(os.path.join(DEPTH_OUTPUT_DIR, "%04i.png" % filename))
        print("Wrote image %i" % filename)
        filename+=1

        # Rosbag is too large, we only keep a certain number of images
        # if count == end_frame:
        #     break 
    arr = np.array(arr)
    arr_reshaped = arr.reshape(arr.shape[0], -1)
    # Didn't wait until it's done since it was pretty slow
    np.savetxt(IMAGE_FILE_PATH, arr_reshaped)
    print("Images saved!")
    loaded_arr = np.loadtxt(IMAGE_FILE_PATH)
    load_original_arr = loaded_arr.reshape(
        loaded_arr.shape[0], loaded_arr.shape[1] // arr.shape[2], arr.shape[2])
    # check the shapes
    print("shape of arr: ", arr.shape)
    print("shape of load_original_arr: ", load_original_arr.shape)
    bag.close()
    return

def bag_to_pose(bagfile, pose_topic, outfile_position, outfile_velocity, start_frame, end_frame):
    """
    Write /joint_states to a file
    """
    # To make sure we read images and poses approximately at the same rate
    offset = 32
    n = start_frame
    position = []
    velocity = []
    with rosbag.Bag(bagfile, 'r') as bag:
        prev = start_frame
        for (topic, msg, ts) in bag.read_messages(topics=str(pose_topic)):
            if msg.header.seq < n:
                continue
            if msg.header.seq - prev <= offset:
                continue
            prev = msg.header.seq
            print("recording frame: ", msg.header.seq)
            reordered_position = [0] * len(msg.position)
            reordered_position[:7] = msg.position[2:]
            reordered_position[-2:] = msg.position[:2]
            reordered_velocity = [0] * len(msg.velocity)
            reordered_velocity[:7] = msg.velocity[2:]
            reordered_velocity[-2:] = msg.velocity[:2]
            
            position.append(reordered_position)
            velocity.append(reordered_velocity)
            n += 1
            if n == end_frame:
                break
        position = np.array(position)
        velocity = np.array(velocity)
        np.savetxt(outfile_position, position)
        np.savetxt(outfile_velocity, velocity)
        # check the shapes
        loaded_position = np.loadtxt(outfile_position)
        loaded_velocity = np.loadtxt(outfile_velocity)
        print("shape of position: ", position.shape)
        print("shape of loaded_position: ", loaded_position.shape)
        print("shape of velocity: ", velocity.shape)
        print("shape of loaded_velocity: ", loaded_velocity.shape)
    print('wrote ' + str(n) + ' imu messages to the file: ' + outfile_position + ' and ' + outfile_velocity) 

def extract_poses_with_timestamps(bagfile, depth_topic, rgb_topic, pose_topic, outfile_position, outfile_velocity, outfile_rgb, start_frame):
    """
    Extract poses from rosbag according to matching timestamps between depth topic and pose topic.
    """
    bridge = CvBridge()
    depth_timestamps = {} # depth topic
    pose_timestamps = {} # pose topic
    final_pose_timestamps = {} # timestamps to extract for pose topic
    rgb_timestamps = {} # rgb topic
    final_rgb_timestamps = {} # timestamps to extract for rgb topic
    position = []
    velocity = []
    n = 0
    m = 0
    rgb_filename = 1
    with rosbag.Bag(bagfile, 'r') as bag:
        for (topic, msg, ts) in bag.read_messages(topics=str(depth_topic)):
            print("processing ", ts)
            if msg.header.stamp.secs not in depth_timestamps.keys():
                depth_timestamps[msg.header.stamp.secs] = []
            depth_timestamps[msg.header.stamp.secs].append(msg.header.stamp.nsecs)
        print("The length of the depth_timestamps is {}".format(len(depth_timestamps)))
        
        # Processing pose topic
        # Get the hashmap for pose topic
        for (topic, msg, ts) in bag.read_messages(topics=str(pose_topic)):
            if msg.header.stamp.secs in depth_timestamps.keys():
                if msg.header.stamp.secs not in pose_timestamps.keys():
                    pose_timestamps[msg.header.stamp.secs] = []
                pose_timestamps[msg.header.stamp.secs].append(msg.header.stamp.nsecs)
        print("Finished processing pose_timestamps")
        
        for secs in tqdm(depth_timestamps.keys()):
            if secs not in final_pose_timestamps.keys():
                final_pose_timestamps[secs] = []
            for nsecs in depth_timestamps[secs]:
                closest_nsecs = math.inf
                result_nsecs = nsecs
                for pose_nsecs in pose_timestamps[secs]:
                    if abs(pose_nsecs - nsecs) < closest_nsecs:
                        result_nsecs = pose_nsecs
                        closest_nsecs = abs(pose_nsecs - nsecs)
                final_pose_timestamps[secs].append(result_nsecs)
        print("Finished recording final_pose_timestamps")

        # Extract poses with the timestamps we want to keep
        for (topic, msg, ts) in bag.read_messages(topics=str(pose_topic)):
            if msg.header.stamp.secs in final_pose_timestamps.keys() and msg.header.stamp.nsecs in final_pose_timestamps[msg.header.stamp.secs]:
                n += 1
                if n < start_frame:
                    continue
                reordered_position = [0] * len(msg.position)
                reordered_position[:7] = msg.position[2:]
                reordered_position[-2:] = msg.position[:2]
                reordered_velocity = [0] * len(msg.velocity)
                reordered_velocity[:7] = msg.velocity[2:]
                reordered_velocity[-2:] = msg.velocity[:2]
                
                position.append(reordered_position)
                velocity.append(reordered_velocity)
                
                print("Processing ", n, "th frame.")
        position = np.array(position)
        velocity = np.array(velocity)
        np.savetxt(outfile_position, position)
        np.savetxt(outfile_velocity, velocity)
        # check the shapes
        loaded_position = np.loadtxt(outfile_position)
        loaded_velocity = np.loadtxt(outfile_velocity)
        print("shape of position: ", position.shape)
        print("shape of loaded_position: ", loaded_position.shape)
        print("shape of velocity: ", velocity.shape)
        print("shape of loaded_velocity: ", loaded_velocity.shape)
        
        # Processing RGB topic
        for (topic, msg, ts) in bag.read_messages(topics=str(rgb_topic)):
            if msg.header.stamp.secs in depth_timestamps.keys():
                if msg.header.stamp.secs not in rgb_timestamps.keys():
                    rgb_timestamps[msg.header.stamp.secs] = []
                rgb_timestamps[msg.header.stamp.secs].append(msg.header.stamp.nsecs)
        print("Finished processing rgb_timestamps")

        for secs in tqdm(depth_timestamps.keys()):
            if secs not in final_rgb_timestamps.keys():
                final_rgb_timestamps[secs] = []
            for nsecs in depth_timestamps[secs]:
                closest_nsecs = math.inf
                result_nsecs = nsecs
                for pose_nsecs in rgb_timestamps[secs]:
                    if abs(pose_nsecs - nsecs) < closest_nsecs:
                        result_nsecs = pose_nsecs
                        closest_nsecs = abs(pose_nsecs - nsecs)
                final_rgb_timestamps[secs].append(result_nsecs)
        print("Finished recording final_rgb_timestamps")

        for (topic, msg, ts) in bag.read_messages(topics=str(rgb_topic)):
            if msg.header.stamp.secs in final_rgb_timestamps.keys() and msg.header.stamp.nsecs in final_rgb_timestamps[msg.header.stamp.secs]:
                m += 1
                if m < start_frame:
                    continue
                cv_img = bridge.imgmsg_to_cv2(msg, desired_encoding="passthrough")
                cv2.imwrite(os.path.join(outfile_rgb, "%04i.png" % rgb_filename), cv_img)
                rgb_filename+=1
                print("Wrote image %i" % m)

    print('wrote ' + str(n) + ' imu messages to the file: ' + outfile_position + ' and ' + outfile_velocity)

def extract_cube_pose(start_frame):
    """
    Extract the pose information of the cube for the start_frame from the rosbag generated by tagslam.
    """
    depth_bag = rosbag.Bag(ROSBAG_NAME, "r")
    bag = rosbag.Bag(ODOM_ROSBAG_NAME, "r")
    secs = 0
    nsecs = 0
    depth_timestamps = {}
    odom_timestamps = {}
    final_odom_timestamps = {}
    for (topic, msg, ts) in depth_bag.read_messages(topics=str(DEPTH_ROS_TOPIC)):
        if msg.header.stamp.secs not in depth_timestamps.keys():
            depth_timestamps[msg.header.stamp.secs] = []
        depth_timestamps[msg.header.stamp.secs].append(msg.header.stamp.nsecs)
    print("The length of the depth_timestamps is {}".format(len(depth_timestamps)))

    for (topic, msg, ts) in bag.read_messages(topics=str(ODOM_ROS_TOPIC)):
        if msg.header.stamp.secs in depth_timestamps.keys():
            if msg.header.stamp.secs not in odom_timestamps.keys():
                odom_timestamps[msg.header.stamp.secs] = []
            odom_timestamps[msg.header.stamp.secs].append(msg.header.stamp.nsecs)
    print("Finished processing pose_timestamps")
    
    for secs in tqdm(depth_timestamps.keys()):
        if secs not in final_odom_timestamps.keys():
            final_odom_timestamps[secs] = []
        for nsecs in depth_timestamps[secs]:
            closest_nsecs = math.inf
            result_nsecs = nsecs
            for pose_nsecs in odom_timestamps[secs]:
                if abs(pose_nsecs - nsecs) < closest_nsecs:
                    result_nsecs = pose_nsecs
                    closest_nsecs = abs(pose_nsecs - nsecs)
            final_odom_timestamps[secs].append(result_nsecs)
    print(final_odom_timestamps)
    
    # Find the timestamp that matches the start_frame of the depth topic
    # for topic, msg, t in bag.read_messages(topics=str(ODOM_ROS_TOPIC)):
    #     closest_nsecs = np.inf
    #     if msg.header.stamp.secs == secs:
    #         if msg.header.stamp.nsecs - nsecs < closest_nsecs:
    #             print('Updating...')
    #             nsecs = msg.header.stamp.nsecs
    #             closest_nsecs = msg.header.stamp.nsecs - nsecs
    frame_id = 1
    for topic, msg, t in bag.read_messages(topics=str(ODOM_ROS_TOPIC)):
        if msg.header.stamp.secs in final_odom_timestamps.keys() and msg.header.stamp.nsecs in final_odom_timestamps[msg.header.stamp.secs]:
            print("Processing frame: ", frame_id)
            if frame_id == start_frame:
                print("Saving frame ", start_frame)
                Q = np.zeros((4, 1))
                Q[0] = msg.pose.pose.orientation.x
                Q[1] = msg.pose.pose.orientation.y
                Q[2] = msg.pose.pose.orientation.z
                Q[3] = msg.pose.pose.orientation.w
                rotation_matrix = quaternion_to_rotation_matrix(Q)[:,:,0]
                position = msg.pose.pose.position
                translation = np.array([[position.x], [position.y], [position.z]])
                result = np.vstack((np.hstack((rotation_matrix, translation)), np.array([0,0,0,1])))
                result = world_to_camera(result)
                np.savetxt(ODOM_FILE_PATH+'%04i.txt'%frame_id, result) #save cube pose in camera frame
                break
            frame_id+=1
    bag.close()
    return

def extract_gt_poses_from_tagslam(depth_bag_file, odom_bag_file, depth_topic, odom_topic, output_dir):
    """
    Extract the pose information of the cube from tagslam to testify the results of BuddleTrack.
    """
    depth_bag = rosbag.Bag(depth_bag_file, "r")
    bag = rosbag.Bag(odom_bag_file, "r")
    depth_timestamps = {} # depth topic
    odom_timestamps = {}
    final_odom_timestamps = {} # timestamps to extract for pose topic
    for (topic, msg, ts) in depth_bag.read_messages(topics=str(depth_topic)):
        if msg.header.stamp.secs not in depth_timestamps.keys():
            depth_timestamps[msg.header.stamp.secs] = []
        depth_timestamps[msg.header.stamp.secs].append(msg.header.stamp.nsecs)
    print("Finished processing depth_timestamps")
    print('secs:', len(depth_timestamps))
    l=0
    for t in depth_timestamps.keys():
        l+=len(depth_timestamps[t])
    print('depth map length:', l)

    # Record the timestamps for calculating angular/linear velocities later
    frame_id = 1
    final_timestamps = []
    for sec in depth_timestamps.keys():
        for nsec in depth_timestamps[sec]:
            final_timestamps.append(np.array([frame_id, sec, nsec]))
            frame_id+=1
    arr = np.array(final_timestamps)
    np.savetxt(TIMESTAMP_FILE_PATH, arr)
    
    # Processing tagslam bag to get timestamps that matches the depth topic
    for (topic, msg, ts) in bag.read_messages(topics=str(odom_topic)):
        if msg.header.stamp.secs in depth_timestamps.keys():
            if msg.header.stamp.secs not in odom_timestamps.keys():
                odom_timestamps[msg.header.stamp.secs] = []
            odom_timestamps[msg.header.stamp.secs].append(msg.header.stamp.nsecs)
    print("Finished processing odom_timestamps")
    
    for secs in tqdm(depth_timestamps.keys()):
        if secs not in final_odom_timestamps.keys():
            final_odom_timestamps[secs] = []
        for nsecs in depth_timestamps[secs]:
            closest_nsecs = math.inf
            result_nsecs = nsecs
            for odom_nsecs in odom_timestamps[secs]:
                if abs(odom_nsecs - nsecs) < closest_nsecs:
                    print("Updating ...")
                    result_nsecs = odom_nsecs
                    closest_nsecs = abs(odom_nsecs - nsecs)
            if result_nsecs in final_odom_timestamps[secs]:
                continue
            final_odom_timestamps[secs].append(result_nsecs)
    print("Finished recording final_pose_timestamps")
    actualy_recorded_timestamps = {}
    frame_id = 1
    for (topic, msg, ts) in bag.read_messages(topics=str(odom_topic)):
        if msg.header.stamp.secs in final_odom_timestamps.keys():
            if msg.header.stamp.secs not in actualy_recorded_timestamps.keys():
                actualy_recorded_timestamps[msg.header.stamp.secs] = []
            if msg.header.stamp.nsecs in final_odom_timestamps[msg.header.stamp.secs]:
                Q = np.zeros((4, 1))
                Q[0] = msg.pose.pose.orientation.x
                Q[1] = msg.pose.pose.orientation.y
                Q[2] = msg.pose.pose.orientation.z
                Q[3] = msg.pose.pose.orientation.w
                rotation_matrix = quaternion_to_rotation_matrix(Q)[:,:,0]
                position = msg.pose.pose.position
                translation = np.array([[position.x], [position.y], [position.z]])
                result = np.vstack((np.hstack((rotation_matrix, translation)), np.array([0,0,0,1])))
                # np.savetxt(output_dir+'%04i.txt'%frame_id, result)
                frame_id+=1
                actualy_recorded_timestamps[msg.header.stamp.secs].append(msg.header.stamp.nsecs)
    
    print('secs:', len(actualy_recorded_timestamps))
    l=0
    for t in actualy_recorded_timestamps.keys():
        l+=len(actualy_recorded_timestamps[t])
    print('l:', l)
    
    i = 0
    for secs in final_odom_timestamps.keys():
        if secs not in actualy_recorded_timestamps.keys():
            print('secs:', secs)
        
        if len(final_odom_timestamps[secs]) != len(actualy_recorded_timestamps[secs]):
            print('a', final_odom_timestamps[secs])
            print('b', actualy_recorded_timestamps[secs])
        for nsecs in final_odom_timestamps[secs]:
            if nsecs not in actualy_recorded_timestamps[secs]:
                print('nsecs:', nsecs)
                i+=1
    print(i)
    bag.close()
    return

if __name__ == '__main__':
    bag_to_depth_images(701)
    # extract_poses_with_timestamps(ROSBAG_NAME, DEPTH_ROS_TOPIC, RGB_ROS_TOPIC, JOINT_STATE_ROS_TOPIC, POSITION_FILE_PATH, VELOCITY_FILE_PATH, RGB_OUTPUT_DIR, 701)
    # extract_cube_pose(701)
    # extract_gt_poses_from_tagslam(ROSBAG_NAME, ODOM_ROSBAG_NAME, DEPTH_ROS_TOPIC, ODOM_ROS_TOPIC, GT_ODOM_FILE_PATH)