import os
import os.path as op
import rosbag
import rospy
import pdb
import imageio
from cv_bridge import CvBridge
import numpy as np
from tqdm import tqdm
from scipy.spatial.transform import Rotation as R

from pydrake.all import MultibodyPlant, Parser, DiagramBuilder, RigidTransform

import file_utils, math_utils


DEPTH_ROS_TOPIC = "/camera/aligned_depth_to_color/image_raw"
JOINT_STATE_ROS_TOPIC = "/panda/joint_states"
RGB_ROS_TOPIC = "/camera/color/image_raw"
ODOM_ROS_TOPIC = "/tagslam/odom/body_box"
TAGSLAM_CAMERA_TOPICS = [
    '/cam_sync/cam0/image_raw/compressed',
    '/cam_sync/cam1/image_raw/compressed',
    '/cam_sync/cam2/image_raw/compressed'
]
ALL_CAMERA_TOPICS = TAGSLAM_CAMERA_TOPICS + [RGB_ROS_TOPIC]
TAGSLAM_CAMERA_INFO_TOPICS = [
    '/cam_sync/cam0/camera_info',
    '/cam_sync/cam1/camera_info',
    '/cam_sync/cam2/camera_info'
]
REALSENSE_CAMERA_INFO_TOPIC = "/camera/color/camera_info"
ALL_CAMERA_INFO_TOPICS = TAGSLAM_CAMERA_INFO_TOPICS + \
    [REALSENSE_CAMERA_INFO_TOPIC]

ODOM_ROSBAG_NAME = "odom_19.bag"  # Rosbag generated by tagslam

# Use half of the frame rate as the tolerance for synchronizing the depth, RGB,
# and TagSLAM pose messages.  The depth messages will be those that strictly
# fall inside the start/end time ranges, while the RGB and TagSLAM pose messages
# will be those that are within the tolerance of the depth messages.  Note that
# this means some RGB and/or TagSLAM poses might be outside the start/end time
# ranges, and there may be some messages that are inside the time range but not
# included as the synchronized messages.  If for any depth message no RGB or
# TagSLAM pose message is found within the tolerance, an error will be raised.
TIME_SYNCHRONIZATION_TOLERANCE = (1.0/30.0)/2
TIME_EXCESS_BUFFER = (1.0/30.0)/2


"""Create a dataset in the format required for the BundleSDF-PLL cyclic
pipeline.  Called by create_dataset.py."""
def extract_synchronized_rgb_and_depth_images(
        start_time: rospy.rostime.Time, end_time: rospy.rostime.Time,
        bag_file: str, rgb_output_dir: str, depth_output_dir: str,
        dataset_dir: str, rgb_topic: str = RGB_ROS_TOPIC,
        depth_topic: str = DEPTH_ROS_TOPIC, depth_offset_mm: int = 0
):
    depth_bag = rosbag.Bag(bag_file, "r")
    bridge = CvBridge()

    start_time = start_time.to_sec()
    end_time = end_time.to_sec()
    print(f"start_time: {start_time}, end_time: {end_time}")

    depth_offset_mm_formatted = np.array([depth_offset_mm]).astype(np.uint16)

    # Extract the RGB and depth images from the depth bag, including all frames
    # within the specified start and end times.
    topics = [depth_topic, rgb_topic]
    depth_images, rgb_images = {}, {}
    for (topic, msg, _t) in depth_bag.read_messages(topics=topics):
        # Skip messages before the start time; stop past the end time.  Add a
        # little extra buffer in case the first or last depth/RGB pairs straddle
        # the start/end times.  These messages will get further filtered during
        # the next synchronization step, which ensures all the depth readings
        # are strictly within the time range.
        if msg.header.stamp.to_sec() < start_time - TIME_EXCESS_BUFFER:
            continue
        if msg.header.stamp.to_sec() > end_time + TIME_EXCESS_BUFFER:
            break

        if topic == depth_topic:
            cv_img_depth = bridge.imgmsg_to_cv2(msg, desired_encoding="16UC1")

            # Incorporate the depth offset, excluding non-returns (depth=0).
            cv_img_depth[cv_img_depth != 0] += depth_offset_mm_formatted
            # If we want to smooth the depth map
            # cv_img_depth = cv2.bilateralFilter(cv_img_depth.astype(
            # np.float32), 20, 20, 10).astype(np.uint16)
            # # diameter, sigmaColor, sigmaSpace

            # Store the result.
            depth_images[msg.header.stamp.to_sec()] = cv_img_depth

        elif topic == rgb_topic:
            cv_img_rgb = bridge.imgmsg_to_cv2(msg, "rgb8")
            rgb_images[msg.header.stamp.to_sec()] = cv_img_rgb

    # Synchronize the depth and RGB images based on the timestamps, writing the
    # synchronized results to the depth and RGB output directories.
    image_i = 1
    bundlesdf_times = []
    for depth_time in tqdm(depth_images, desc='Writing synchronized depth and RGB images'):
        # Strictly filter for depth readings within the time range.  Note that
        # the closest RGB reading might be slightly outside this range.
        if depth_time < start_time or depth_time > end_time:
            print('Skipping frame outside time range.')
            continue

        closest_rgb_time = min(
            rgb_images.keys(),
            key=lambda t: abs(t - depth_time)
        )
        diff = abs(closest_rgb_time - depth_time)
        if diff <= TIME_SYNCHRONIZATION_TOLERANCE:
            imageio.imwrite(
                op.join(depth_output_dir, f'{image_i:04d}.png'),
                np.uint16(depth_images[depth_time])
            )
            imageio.imwrite(
                op.join(rgb_output_dir, f'{image_i:04d}.png'),
                rgb_images[closest_rgb_time]
            )
            # print(f'Wrote synchronized depth and RGB images {image_i}')
            image_i += 1
            bundlesdf_times.append(depth_time)

        else:
            raise RuntimeError(f'ERROR: Time difference between RGB and ' + \
                               f'depth images too great ({diff} > ' + \
                               f'{TIME_SYNCHRONIZATION_TOLERANCE}).')

    # Write the BundleSDF timestamps to file.
    np.savetxt(op.join(dataset_dir, 'bundlesdf_timestamps.txt'),
               bundlesdf_times)

    depth_bag.close()

def extract_tagslam_poses(
        start_time: rospy.rostime.Time, end_time: rospy.rostime.Time,
        bag_file: str, odom_topic: str, tagslam_pose_output_dir: str
):
    odom_bag = rosbag.Bag(bag_file, "r")

    start_time = start_time.to_sec()
    end_time = end_time.to_sec()
    print(f"start_time: {start_time}, end_time: {end_time}")

    # Extract the TagSLAM poses from the odom bag, storing them exactly as
    # reported in the bag.
    poses, times = [], []
    for (_topic, msg, _t) in tqdm(odom_bag.read_messages(topics=[odom_topic])):
        # Skip messages before the start time; stop past the end time.  Add
        # extra buffer in case the first or last closest TagSLAM pose message
        # is a bit outside this range.  This will get resolved afterwards with a
        # synchronization step.
        if msg.header.stamp.to_sec() < start_time - 10*TIME_EXCESS_BUFFER:
            continue
        if msg.header.stamp.to_sec() > end_time + 10*TIME_EXCESS_BUFFER:
            break

        # Store the pose from the message.
        pose = np.zeros((7,))
        pose[0] = msg.pose.pose.position.x
        pose[1] = msg.pose.pose.position.y
        pose[2] = msg.pose.pose.position.z
        pose[3] = msg.pose.pose.orientation.x
        pose[4] = msg.pose.pose.orientation.y
        pose[5] = msg.pose.pose.orientation.z
        pose[6] = msg.pose.pose.orientation.w
        poses.append(pose)
        times.append(msg.header.stamp.to_sec())

    print(f'Extracted {len(poses)} TagSLAM poses from the odometry bag.')
    tagslam_poses = np.array(poses)
    tagslam_times = np.array(times)

    for i, pose in enumerate(tagslam_poses):
        np.savetxt(op.join(tagslam_pose_output_dir, f'{i+1:04d}.txt'), pose)

    # Lastly, write a tagslam.txt file that contains the TagSLAM poses and
    # timestamps.
    tagslam_times = np.array(tagslam_times).reshape(-1, 1)
    tagslam_poses = np.array(tagslam_poses).reshape(-1, 7)
    tagslam_data = np.concatenate((tagslam_times, tagslam_poses), axis=1)
    np.savetxt(op.join(tagslam_pose_output_dir, 'tagslam.txt'), tagslam_data)
    print('Wrote TagSLAM poses and timestamps as tagslam.txt.')

    odom_bag.close()

"""Extract the Franka joint states from a robot bag file between start and end
times.  Called by create_dataset.py for interactive robot experiments."""
def extract_franka_joints(
        start_time: rospy.rostime.Time, end_time: rospy.rostime.Time,
        bag_file: str, franka_joint_states_output_dir: str
):
    robot_bag = rosbag.Bag(bag_file, "r")

    start_time = start_time.to_sec()
    end_time = end_time.to_sec()
    print(f"start_time: {start_time}, end_time: {end_time}")

    # Extract the joint states, storing them exactly as reported in the bag.
    joint_angles, joint_velocities, joint_efforts, times = [], [], [], []
    joint_names = None
    for (_topic, msg, _t) in tqdm(robot_bag.read_messages(
        topics=[JOINT_STATE_ROS_TOPIC])):
        # Skip messages before the start time; stop past the end time.  Add
        # extra buffer in case the first or last closest joint state pose
        # message is a bit outside this range.  This will get resolved
        # afterwards with a synchronization step.
        if msg.header.stamp.to_sec() < start_time - TIME_EXCESS_BUFFER:
            continue
        if msg.header.stamp.to_sec() > end_time + TIME_EXCESS_BUFFER:
            break

        if joint_names is None:
            joint_names = msg.name

        # Store the joint information from the message.
        joint_angles.append(list(msg.position))
        joint_velocities.append(list(msg.velocity))
        joint_efforts.append(list(msg.effort))
        times.append(msg.header.stamp.to_sec())

    print(f'Extracted {len(joint_angles)} joint states from the odometry bag.')

    # Write the joint states and timestamps to file.
    joint_times = np.array(times).reshape(-1, 1)
    joint_angles = np.array(joint_angles).reshape(-1, len(joint_names))
    joint_velocities = np.array(joint_velocities).reshape(-1, len(joint_names))
    joint_efforts = np.array(joint_efforts).reshape(-1, len(joint_names))
    np.savetxt(op.join(franka_joint_states_output_dir, 'joint_times.txt'),
               joint_times)
    np.savetxt(op.join(franka_joint_states_output_dir, 'joint_angles.txt'),
               joint_angles)
    np.savetxt(op.join(franka_joint_states_output_dir, 'joint_velocities.txt'),
               joint_velocities)
    np.savetxt(op.join(franka_joint_states_output_dir, 'joint_efforts.txt'),
               joint_efforts)
    with open(op.join(franka_joint_states_output_dir, 'joint_names.txt'), 'w') \
        as f:
        f.write('\n'.join(joint_names))
    print('Wrote Franka joint states and times to file.')

    # Convert the joint angles to end effector positions.
    ee_positions = convert_franka_joints_to_ee_positions(
        joint_angles, joint_names)
    np.savetxt(op.join(franka_joint_states_output_dir, 'ee_positions.txt'),
               ee_positions)
    print('Wrote Franka end effector positions to file.')

    robot_bag.close()

"""Convert Franka joint angles to the 3D world position of the end effector's
center.  Assumes the Franka base is at the world origin, and uses the Franka and
end effector geometry defined in assets/franka_with_ee.urdf.  This uses Drake to
build a plant with the Franka, set the plant's joint angles, then query the
position of the end effector tip's origin."""
def convert_franka_joints_to_ee_positions(
        joint_angles: np.ndarray, joint_names: list):
    # Build a Drake plant with the Franka at the world origin.
    builder = DiagramBuilder()
    plant = MultibodyPlant(time_step=0.0)
    parser = Parser(plant)
    parser.AddModels(file_utils.franka_filepath())
    plant.WeldFrames(
        plant.world_frame(), plant.GetFrameByName("panda_link0"),
        RigidTransform()
    )
    plant.Finalize()
    builder.AddSystem(plant)
    builder.Build()
    context = plant.CreateDefaultContext()

    # Get the indices of the joint names that correspond to the Franka joints.
    sim_joint_names = plant.GetPositionNames()
    sim_joint_indices = -1 * np.ones((len(sim_joint_names),), dtype=int)
    for sim_joint_index, sim_joint_name in enumerate(sim_joint_names):
        for recorded_joint_index, recorded_joint_name in enumerate(joint_names):
            if recorded_joint_name in sim_joint_name:
                sim_joint_indices[sim_joint_index] = recorded_joint_index
                break
    assert np.all(sim_joint_indices >= 0), 'Failed to find all joint ' + \
        f'indices: {sim_joint_names=} vs. {joint_names=}.'

    # Prepare to store the end effector positions.
    ee_positions = np.zeros((joint_angles.shape[0], 3))

    # Iterate over all the joint angles and read the corresponding EE position.
    for i, joint_angle in enumerate(joint_angles):
        plant.SetPositions(context, joint_angle[sim_joint_indices])
        ee_positions[i] = plant.EvalBodyPoseInWorld(
            context, plant.GetBodyByName("end_effector_tip")).translation()

    return ee_positions

"""Write the initial TagSLAM origin pose, as reported by TagSLAM, expressed in
camera frame.  This gets stored as a 4x4 transformation matrix titled 0000.txt
in the annotated_poses directory.  Called by create_dataset.py."""
def save_initial_tagslam_pose_in_camera_frame(
        synced_tagslam_world_poses_dir: str, annotated_poses_dir: str,
        cam_trans: np.ndarray, cam_rot_axis_angle: np.ndarray
) -> None:
    """Given the extracted TagSLAM poses in world frame stored in
    synced_tagslam.txt, write the 0th annotated pose as the TagSLAM origin's
    initial pose in camera frame.

    Args:
        synced_tagslam_world_poses_dir
        annotated_poses_dir
        cam_trans
        cam_rot_axis_angle
    """
    # Load the previously extracted TagSLAM world-frame trajectory.
    data = np.loadtxt(
        os.path.join(synced_tagslam_world_poses_dir, "synced_tagslam.txt"))

    # Get the first pose by eliminating the timestamp and all subsequent poses.
    init_pose = data[0, 1:]

    # Represent initial pose as a 4x4 transformation matrix in camera frame.
    mat = math_utils.pos_quat_to_trans_mat(init_pose)
    mat_cam = math_utils.world_to_camera(mat, cam_trans, cam_rot_axis_angle)

    # Write the 4x4 transformation matrix in annotated poses directory.
    np.savetxt(os.path.join(annotated_poses_dir, "0000.txt"), mat_cam)
    print(f'Initial pose saved to {annotated_poses_dir}/0000.txt.')


"""Extract the depth images from a depth bag file between start and end times.
Called by compute_table_offsets.py."""
def extract_depth_images(start_time, end_time, depth_bag_file):
    depth_bag = rosbag.Bag(depth_bag_file, "r")

    bridge = CvBridge()

    depth_times, depth_msgs = [], []
    for (_topic, msg, _ts) in depth_bag.read_messages(
        topics=str(DEPTH_ROS_TOPIC)
    ):
        if msg.header.stamp < start_time:
            continue
        if msg.header.stamp >= end_time:
            break

        depth_times.append(msg.header.stamp.to_sec())

        image = bridge.imgmsg_to_cv2(msg, desired_encoding="passthrough")
        depth_msgs.append(image)

    return depth_times, depth_msgs


"""Extract the RGB and BW images from a raw bag file between start and end times
Called by adjust_and_view_tagslam_offset.py."""
def extract_camera_images_and_poses(
        start_time, end_time, raw_bag_file, odom_bag_file, odom_topic):
    raw_bag = rosbag.Bag(raw_bag_file, "r")
    odom_bag = rosbag.Bag(odom_bag_file, "r")

    poses, pose_times = [], []
    for (_topic, msg, t) in odom_bag.read_messages(topics=[odom_topic]):
        if msg.header.stamp < start_time:  continue
        if msg.header.stamp > end_time:  break

        # Store the pose from the message.
        pose = np.zeros((7,))
        pose[0] = msg.pose.pose.position.x
        pose[1] = msg.pose.pose.position.y
        pose[2] = msg.pose.pose.position.z
        pose[3] = msg.pose.pose.orientation.x
        pose[4] = msg.pose.pose.orientation.y
        pose[5] = msg.pose.pose.orientation.z
        pose[6] = msg.pose.pose.orientation.w
        poses.append(pose)
        pose_times.append(msg.header.stamp.to_sec())

    bridge = CvBridge()

    # Have a 2D list where the first index is the camera number and the second
    # index is the list of times/messages for that camera.
    image_times = {'cam0': [], 'cam1': [], 'cam2': [], 'realsense': []}
    image_msgs = {'cam0': [], 'cam1': [], 'cam2': [], 'realsense': []}
    for (topic, msg, ts) in raw_bag.read_messages(topics=ALL_CAMERA_TOPICS):
        if ts.to_sec() < start_time.to_sec():  continue
        if ts.to_sec() > end_time.to_sec():  break

        if topic==RGB_ROS_TOPIC:
            camera_name = 'realsense'
            image = bridge.imgmsg_to_cv2(msg, desired_encoding="passthrough")

        else:
            camera_name = topic.split("/")[2]
            image = bridge.compressed_imgmsg_to_cv2(
                msg, desired_encoding="passthrough")

        image_times[camera_name].append(ts.to_sec())
        image_msgs[camera_name].append(image)

    return pose_times, poses, image_times, image_msgs


"""Extract the RGB images and robot end effector locations from a raw bag file
between start and end times.  Called by inspect_camera_alignments.py."""
def extract_camera_images_and_ee_locations(
        start_time, end_time, robot_bag_file):
    robot_bag = rosbag.Bag(robot_bag_file, "r")

    bridge = CvBridge()

    joint_times, joint_angles = [], []
    joint_names = None
    image_times, image_msgs = [], []
    for (topic, msg, ts) in robot_bag.read_messages(
        topics=[JOINT_STATE_ROS_TOPIC, RGB_ROS_TOPIC]):
        # Skip messages before the start time; stop past the end time.
        if ts.to_sec() < start_time.to_sec():  continue
        if ts.to_sec() > end_time.to_sec():  break

        if topic == JOINT_STATE_ROS_TOPIC:
            if joint_names is None:
                joint_names = msg.name

            # Store the joint information from the message.
            joint_times.append(ts.to_sec())
            joint_angles.append(list(msg.position))

        elif topic == RGB_ROS_TOPIC:
            image = bridge.imgmsg_to_cv2(msg, desired_encoding="passthrough")

            image_times.append(ts.to_sec())
            image_msgs.append(image)

    # Convert the joint angles to end effector positions.
    joint_angles = np.array(joint_angles).reshape(-1, len(joint_names))
    ee_positions = convert_franka_joints_to_ee_positions(
        joint_angles, joint_names)

    return joint_times, ee_positions, image_times, image_msgs


"""Extract the TagSLAM camera poses from an odometry bag file, which features
the world-to-camX transformations in the /tf topic."""
def get_tagslam_camera_extrinsics(odom_bag_file):
    odom_bag = rosbag.Bag(odom_bag_file, "r")

    # Get the camera extrinsics from the /tf topic.
    extrinsics = {'cam0': None, 'cam1': None, 'cam2': None}
    for (_topic, msg, _t) in odom_bag.read_messages(topics=["/tf"]):
        for transform in msg.transforms:
            if transform.child_frame_id in extrinsics.keys():
                camera = transform.child_frame_id
                assert transform.header.frame_id == 'world', 'Expected ' + \
                    f'frame_id world but got {transform.header.frame_id}.'
                extrinsics[camera] = transform.transform

                if extrinsics['cam0'] and extrinsics['cam1'] and \
                        extrinsics['cam2']:
                    break

    cam0_trans, cam0_axis_angle = \
        math_utils.ros_geometry_transform_to_camera_extrinsics(
            extrinsics['cam0'])
    cam1_trans, cam1_axis_angle = \
        math_utils.ros_geometry_transform_to_camera_extrinsics(
            extrinsics['cam1'])
    cam2_trans, cam2_axis_angle = \
        math_utils.ros_geometry_transform_to_camera_extrinsics(
            extrinsics['cam2'])

    return cam0_trans, cam0_axis_angle, cam1_trans, cam1_axis_angle, \
        cam2_trans, cam2_axis_angle


"""Extract the TagSLAM camera intrinsics from a raw bag file, which features the
intrinsics at the camera_info topics."""
def get_all_camera_intrinsics(raw_bag_file):
    raw_bag = rosbag.Bag(raw_bag_file, "r")

    # Get the camera extrinsics from the /tf topic.
    intrinsics = {'cam0': None, 'cam1': None, 'cam2': None, 'realsense': None}
    for (_topic, msg, _t) in raw_bag.read_messages(
        topics=ALL_CAMERA_INFO_TOPICS):
        camera = 'realsense' if _topic==REALSENSE_CAMERA_INFO_TOPIC else \
            msg.header.frame_id[-4:]
        if type(intrinsics[camera]) != np.ndarray:
            intrinsics[camera] = np.array(msg.P)

            if (type(intrinsics['cam0']) != np.ndarray) and \
               (type(intrinsics['cam1']) != np.ndarray) and \
               (type(intrinsics['cam2']) != np.ndarray) and \
               (type(intrinsics['realsense']) != np.ndarray):
                break

    return intrinsics



if __name__ == "__main__":
    extract_franka_joints(
        None, None,
        '/home/bibit/vision/bundlenets/cnets-data-generation/rosbags/' + \
        'robot_bags/vision_bags/bakingbox_sticky/raw_201.bag',
        None)
