
import cv2
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.backends.backend_agg import FigureCanvasAgg
import os
import os.path as op
from copy import deepcopy
from tqdm import tqdm

def create_plot(data, frame_index, title=None):
    ### Find the relative index of frame_index in the data x. 
    ### If frame_index < x.min(), then the plot will be empty.
    ### If frame_index > x.max(), then the plot will be the same as the last frame.

    x = data['x']
    fig, ax = plt.subplots(figsize=(6, 4))
    if frame_index < x.min():
        pass
    else:
        ### Find the index of the frame_index in the data x, 
        ### such that x[index] <= frame_index < x[index+1]
        index = np.searchsorted(x, frame_index, side='right') - 1
        len_indiced = index + 1

        y_keys = list(data.keys())
        y_keys = [y_key for y_key in y_keys if y_key != 'x']
        y_keys.sort()
        x = deepcopy(data['x'][:len_indiced])
        y_dict = {y: deepcopy(data[y][:len_indiced]) for y in y_keys}
        y_arrays = [y_dict[y] for y in y_keys]
        if len(y_arrays[0]) == 1:
            ### Plot with marker because the line won't be visible
            for y in y_keys:
                ax.plot(x, y_dict[y], marker='o', label=y)
        else:
            for y in y_keys:
                ax.plot(x, y_dict[y], label=y)
        if x.min() == x.max():
            ax.set_xlim(x.min(), x.max() + 1)
        else:
            ax.set_xlim(x.min(), x.max())
        ax.set_ylim(min(y.min() for y in y_arrays), max(y.max() for y in y_arrays))
        ax.legend()

    if title is not None:
        ax.set_title(title)
    ax.set_xlabel('Frame')
    ### Use x tick minimal interval to 1
    ax.xaxis.set_major_locator(plt.MaxNLocator(integer=True))

    canvas = FigureCanvasAgg(fig)
    canvas.draw()
    plot_image = np.frombuffer(canvas.buffer_rgba(), dtype='uint8')
    plot_image = plot_image.reshape(canvas.get_width_height()[::-1] + (4,))
    plot_image = plot_image[:, :, :3]
    plt.close(fig)
    return plot_image

def sync_video_and_plots(video_path, data_paths, output_path):
    cap = cv2.VideoCapture(video_path)
    fps = int(cap.get(cv2.CAP_PROP_FPS))
    width = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
    height = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
    frame_count = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))
    
    data_list = [np.load(path) for path in data_paths]
    title_list = [path.split('/')[-1].split('.')[0] for path in data_paths]
    num_plots = len(data_paths)
    
    # Determine the number of columns and rows
    cols = (num_plots + 1) // 2
    rows = 2 if num_plots > 1 else 1
    
    # Resize and arrange the plots
    plot_height = height // rows
    plot_width = width // 2

    fourcc = cv2.VideoWriter_fourcc(*'mp4v')
    # Make sure the output path's dir is a directory
    if not os.path.isdir(os.path.dirname(output_path)):
        os.makedirs(os.path.dirname(output_path))
    out = cv2.VideoWriter(output_path, fourcc, fps, (width + plot_width * cols, height))
    
    tqdm.write("Processing video...")
    
    frame_count = 0
    with tqdm(total=frame_count) as pbar:
        while True:
            ret, frame = cap.read()
            if not ret:
                break
            
            plots = []
            for data, title in zip(data_list, title_list):
                plot = create_plot(data, frame_count, title)
                plots.append(plot)
            
            combined_plots = np.zeros((height, plot_width * cols, 3), dtype=np.uint8)
            
            for i, plot in enumerate(plots):
                resized_plot = cv2.resize(plot, (plot_width, plot_height))
                row = i % rows
                col = i // rows
                combined_plots[row * plot_height:(row + 1) * plot_height, col * plot_width:(col + 1) * plot_width] = resized_plot
            
            output_frame = np.hstack((frame, combined_plots))
            out.write(output_frame)
            
            frame_count += 1
            pbar.update(1)
        
    
    cap.release()
    out.release()

    ### run ffmpeg to convert the output video to mp4
    os.system(f"ffmpeg -i {output_path} -vcodec h264 {output_path.replace('.mp4', '_.mp4')}")
    os.remove(output_path)
    os.rename(output_path.replace('.mp4', '_.mp4'), output_path)

if __name__ == "__main__":

    # Generated by overlay_videos.py or conversion_bsdf_to_pll.py
    input_video_root = "/mnt/data0/minghz/repos/bundlenets/cnets-data-generation/consolidated_results/overlay_videos"
    video_path = op.join(input_video_root, "1023_robot_oatly_5_00_nerf_00_1.mp4")
    
    data_root = "/mnt/data0/minghz/repos/bundlenets/dair_pll/results/vision_robot_oatly/robot_oatly_50/bundlesdf_iteration_1"
    data_paths = [op.join(data_root, "pll_id_t02/losses_curve.npz"),
                    # op.join(data_root, "pll_id_t01/losses_curve_gt_mesh.npz"),
                    op.join(data_root, "pll_id_t02/phis_curve.npz"),
                    # op.join(data_root, "pll_id_t01/phis_curve_gt_mesh.npz"),
                    op.join(data_root, "pll_id_t02/normalfs_curve.npz"),
                    # op.join(data_root, "pll_id_t01/normalfs_curve_gt_mesh.npz"),
                    op.join(data_root, "pll_id_t02/vs_curve.npz"),
                    # op.join(data_root, "pll_id_t01/vs_curve_gt_mesh.npz")
    ]
    
    output_video_root = "/mnt/data0/minghz/repos/bundlenets/cnets-data-generation/consolidated_results/synced_videos"
    output_path = op.join(output_video_root, "1023_robot_oatly_50_00_nerf_00_1_pll_t02_combo.mp4")
    
    sync_video_and_plots(video_path, data_paths, output_path)
