import copy
import numpy as np
import math
from PIL import Image
import matplotlib.pyplot as plt 
import imageio
from tqdm import tqdm
from PIL import Image
import glob
import cv2

def filter(real_img, sim_img):
    """
    Filter the simulated image from the real depth image.
    """
    masked_img = np.subtract(real_img, sim_img)
    return masked_img

def generate_depth_img_without_robot(depth_dir, mask_dir, filtered_depth_dir):
    """
    Filter out robot from depth image with the generated mask.
    :param str depth_dir: Directory to the original depth image from rosbag.
    :param str mask_dir: Directory to the mask generated by urdf_filter.
    :param str filtered_depth_dir: Directory to save the filtered depth image.
    """
    depth_img = np.loadtxt(depth_dir)
    # depth_img = Image.open(depth_dir)
    mask_img = Image.open(mask_dir)
    depth_array = np.array(depth_img)
    mask_array = np.array(mask_img)
    filtered_depth = copy.deepcopy(depth_array*1000)
    for i in range(mask_array.shape[0]):
        for j in range(mask_array.shape[1]):
            if mask_array[i][j] == 255:
                filtered_depth[i][j] = 0
    # plt.imshow(filtered_depth)
    # plt.colorbar()
    # plt.show()
    imageio.imwrite(filtered_depth_dir, filtered_depth.astype(np.uint16))
    return filtered_depth

def generate_rgb_image_without_robot(rgb_dir, mask_dir, filtered_rgb_dir):
    """
    Filter out robot from rgb image with the generated mask.
    :param str rgb_dir: Directory to the original rgb image from rosbag.
    :param str mask_dir: Directory to the mask generated by urdf_filter.
    :param str filtered_rgb_dir: Directory to save the filtered rgb image.
    """
    rgb_img = Image.open(rgb_dir)
    mask_img = Image.open(mask_dir)
    rgb_array = np.array(rgb_img)
    mask_array = np.array(mask_img)
    filtered_rgb = copy.deepcopy(rgb_array)
    for i in range(mask_array.shape[0]):
        for j in range(mask_array.shape[1]):
            if mask_array[i][j] == 255:
                filtered_rgb[i][j][0] = 0
                filtered_rgb[i][j][1] = 0
                filtered_rgb[i][j][2] = 0
    # plt.imshow(filtered_rgb)
    # plt.show()
    imageio.imwrite(filtered_rgb_dir, filtered_rgb)
    return filtered_rgb

def import_data(img_file, position_file, velocity_file):
    """
    Load data generated from rosbag.
    """
    # images = np.loadtxt(img_file) #importing images is very slow
    positions = np.loadtxt(position_file)
    velocities = np.loadtxt(velocity_file)
    print("position and velocities imported!")
    return positions, velocities

def write_real_depth_as_txt(start_frame, end_frame):
    """
    Save real depth txt at once since image I/O is very slow. 
    """
    img_dir = "./depth_data/images.txt" #depth image in the form of txt
    loaded_arr = np.loadtxt(img_dir)
    load_original_arr = loaded_arr.reshape(
    loaded_arr.shape[0], loaded_arr.shape[1] // 640, 640)
    print("Done loading images.")
    for frame_id in tqdm(range(start_frame, end_frame)):
        real_depth_dir = "./depth_data/real_depth_frame00000{}.txt".format(frame_id)
        print("frame_id", frame_id)
        real = load_original_arr[frame_id]
        np.savetxt(real_depth_dir, real)

def axis_angle_to_rotation_matrix(axis, theta):
    """
    Return the rotation matrix associated with counterclockwise rotation about
    the given axis by theta radians.
    """
    axis = np.asarray(axis)
    axis = axis / math.sqrt(np.dot(axis, axis))
    a = math.cos(theta / 2.0)
    b, c, d = -axis * math.sin(theta / 2.0)
    aa, bb, cc, dd = a * a, b * b, c * c, d * d
    bc, ad, ac, ab, bd, cd = b * c, a * d, a * c, a * b, b * d, c * d
    return np.array([[aa + bb - cc - dd, 2 * (bc + ad), 2 * (bd - ac)],
                     [2 * (bc - ad), aa + cc - bb - dd, 2 * (cd + ab)],
                     [2 * (bd + ac), 2 * (cd - ab), aa + dd - bb - cc]])

def rotation_matrix_to_euler(R):
    beta = -np.arcsin(R[2,0])
    alpha = np.arctan2(R[2,1]/np.cos(beta),R[2,2]/np.cos(beta))
    gamma = np.arctan2(R[1,0]/np.cos(beta),R[0,0]/np.cos(beta))
    return np.array((alpha, beta, gamma))

def get_translation_between_pcd_and_base(x, y, z, K, R, T):
    """
    The origin of the point cloud is at (0,0,0) (where the mesh_frame is), whereas the frame of the base is at the base of the robot in ROS.
    """
    X, Y, Z = point_cloud_to_world(x, y, z, K, R, T, depth_scale=1000)
    return X, Y, Z

def world_to_image(point, K, R, T):
    """
    :param point: 3*1 array 
    :param K: 3*3 intrinsic matrix 
    :param R: 3*3 rotation matrix
    :param T: 3*1 translation matrix
    """
    # 3dpoint tmp = cameraintrinsic(3x3) * rotationvect(1x3) * xyz(3x1) + cameraintrinsic(3x3)*translation(3,1)
    # 2dpoint screen = tmp.x/tmp.z, tmp.y / tmp.z
    world_coord = K @ R @ point + K @ T
    return world_coord[0] / world_coord[2], world_coord[1] / world_coord[2]

def point_cloud_to_world(x, y, z, K, R, T, depth_scale=1000):
    """
    Transform (0,0,0) in point cloud back to world coordinates according to
    z = d / depth_scale = -X / depth_scale
    x = (u - cx) * z / fx
    y = (v - cy) * z / fy
    """
    fx, fy = K[0][0], K[1][1]
    cx, cy = K[0][2], K[1][2]
    d = z * depth_scale
    u = (x * fx) / z + cx
    v = y * fy / z + cy
    X, Y, Z = -d, u, v
    return X, Y, Z

def world_to_point_cloud(X, Y, Z, K, R, T, depth_scale=1000):  
    """
    World coordinate = (X, Y, Z). In world coordinate, d is in -X.
    u = 1/Z * [fx, 0, cz] @ R0 * X
    v = 1/Z * [0, fy, cy] @ R1 * Y
    Transform depth image to point cloud (in the image frame)
    z = d / depth_scale = -X / depth_scale
    x = (u - cx) * z / fx
    y = (v - cy) * z / fy
    """
    # u = 1/Z * (K[0] @ R[:, 0]) * X
    # v = 1/Z * (K[1] @ R[:, 1]) * Y
    u, v = world_to_image(np.array([[X], [Y], [Z]]), K, R, T)
    z = -X / depth_scale
    x = (u - K[0][1]) * z / K[0][0]
    y = (v - K[1][2]) * z / K[1][1]
    z = -X / depth_scale
    return x, y, z

def render_gif():
    """
    Make pngs into a gif.
    """
    frames = []
    for frame_id in range(1, 4432):
        name = "./cube_data/screen_image_frame00000{}.png".format(frame_id)
        new_frame = Image.open(name)
        frames.append(new_frame)
    # Save into a GIF file that loops forever
    frames[0].save('./png_to_gif.gif', format='GIF',
                append_images=frames[1:],
                save_all=True,
                duration=300, loop=0)

def render_video():
    """
    Make pngs into a video for easy view.
    """
    img_array = []
    for filename in glob.glob('C:/New folder/Images/*.jpg'):
        img = cv2.imread(filename)
        height, width, layers = img.shape
        size = (width,height)
        img_array.append(img)
    out = cv2.VideoWriter('project.avi',cv2.VideoWriter_fourcc(*'DIVX'), 15, size)
    for i in range(len(img_array)):
        out.write(img_array[i])
    out.release()

def main():
    # for frame_id in tqdm(range(1, 4432)):
    #     real_depth_file = "./depth_data/real_depth_frame00000{}.txt".format(frame_id)
    #     mask_image_file = "./mask_data/mask_frame00000{}.png".format(frame_id)
    #     filtered_depth_file = "./filtered_data/depth_without_robot_frame00000{}.png".format(frame_id)
    #     generate_depth_img_without_robot(real_depth_file, mask_image_file, filtered_depth_file)
    #     rgb_image_file = "./rgb_data/frame%06i.png" % frame_id
    #     filtered_rgb_file = "./filtered_data/rgb_without_robot_frame00000{}.png".format(frame_id)
    #     generate_rgb_image_without_robot(rgb_image_file, mask_image_file, filtered_rgb_file)
    frame_id = 104
    real_depth_file = "./depth_data/real_depth_frame00000{}.txt".format(frame_id)
    mask_image_file = "./dilated_mask_data/frame00000{}.png".format(frame_id)
    filtered_depth_file = "./filtered_data/depth_without_robot_frame00000{}.png".format(frame_id)
    generate_depth_img_without_robot(real_depth_file, mask_image_file, filtered_depth_file)
    rgb_image_file = "./rgb_data/frame%06i.png" % frame_id
    filtered_rgb_file = "./filtered_data/rgb_without_robot_frame00000{}.png".format(frame_id)
    generate_rgb_image_without_robot(rgb_image_file, mask_image_file, filtered_rgb_file)

if __name__ == "__main__":
    main()