import numpy as np
import math
from PIL import Image
import matplotlib.pyplot as plt 

TABLE_LENGTH = 182.8/100 #in meters
TABLE_WIDTH = 91.3/100
TABLE_HEIGHT = 73.2/100
ROBOT_TO_LENGTH = 46.9/100 # robot base to long side of table
ROBOT_TO_WIDTH = 33.7/100 # robot base to short side of table
ROBOT_TO_HEIGHT = 1/100 # height from robot base to table surface
CAMERA_X = 1.14164360
CAMERA_Y = 0.15815239
CAMERA_Z = 0.66422200
CUBE_LENGTH = 10.2/100
ROBOT_BASE_LENGTH = 10/100 # this is inaccurate

def filter(real_img, sim_img):
    """
    Filter the simulated image from the real depth image.
    """
    masked_img = np.subtract(real_img, sim_img)
    return masked_img

def generate_depth_img_without_robot(depth_dir, mask_dir):
    """
    Filter out robot from depth image with the generated mask.
    :param str depth_dir: Directory to the original depth image from rosbag.
    :param str mask_dir: Directory to the mask generated by urdf_filter.
    """
    depth_img = np.loadtxt('./aligned_data/real_depth.txt')
    # depth_img = Image.open(depth_dir)
    mask_img = Image.open(mask_dir)
    depth_array = np.array(depth_img)
    mask_array = np.array(mask_img)
    filtered_depth = np.subtract(depth_array, mask_array)
    plt.imshow(filtered_depth)
    plt.colorbar()
    plt.show()
    # im = Image.fromarray(filtered_depth)
    # im.save("./depth_without_robot.png")
    plt.imsave('./depth_without_robot.png', filtered_depth.astype(np.uint16))
    return filtered_depth

def generate_rgb_image_without_robot(rgb_dir, mask_dir):
    """
    Filter out robot from rgb image with the generated mask.
    :param str rgb_dir: Directory to the original rgb image from rosbag.
    :param str mask_dir: Directory to the mask generated by urdf_filter.
    """
    rgb_img = Image.open(rgb_dir)
    mask_img = Image.open(mask_dir)
    rgb_array = np.array(rgb_img)
    mask_img_ = np.zeros((np.array(mask_img).shape[0], np.array(mask_img).shape[1], 3))
    mask_img_[:,:,0] = mask_img
    mask_img_[:,:,1] = mask_img
    mask_img_[:,:,2] = mask_img
    mask_array = np.array(mask_img_)
    filtered_rgb = np.subtract(rgb_array, mask_array)
    plt.imshow(filtered_rgb)
    plt.show()
    # im = Image.fromarray(filtered_rgb)
    im = Image.fromarray((filtered_rgb * 255).astype(np.uint8))
    if im.mode != 'RGB':
        im = im.convert('RGB')
    im.save("./rgb_without_robot.png")
    return filtered_rgb

def import_data(img_file, position_file, velocity_file):
    """
    Load data generated from rosbag.
    """
    images = np.loadtxt(img_file)
    positions = np.loadtxt(position_file)
    velocities = np.loadtxt(velocity_file)
    return images, positions, velocities

def axis_angle_to_rotation_matrix(axis, theta):
    """
    Return the rotation matrix associated with counterclockwise rotation about
    the given axis by theta radians.
    """
    axis = np.asarray(axis)
    axis = axis / math.sqrt(np.dot(axis, axis))
    a = math.cos(theta / 2.0)
    b, c, d = -axis * math.sin(theta / 2.0)
    aa, bb, cc, dd = a * a, b * b, c * c, d * d
    bc, ad, ac, ab, bd, cd = b * c, a * d, a * c, a * b, b * d, c * d
    return np.array([[aa + bb - cc - dd, 2 * (bc + ad), 2 * (bd - ac)],
                     [2 * (bc - ad), aa + cc - bb - dd, 2 * (cd + ab)],
                     [2 * (bd + ac), 2 * (cd - ab), aa + dd - bb - cc]])

def rotation_matrix_to_euler(R):
    beta = -np.arcsin(R[2,0])
    alpha = np.arctan2(R[2,1]/np.cos(beta),R[2,2]/np.cos(beta))
    gamma = np.arctan2(R[1,0]/np.cos(beta),R[0,0]/np.cos(beta))
    return np.array((alpha, beta, gamma))

def get_translation_between_pcd_and_base(x, y, z, K, R, T):
    """
    The origin of the point cloud is at (0,0,0) (where the mesh_frame is), whereas the frame of the base is at the base of the robot in ROS.
    """
    X, Y, Z = point_cloud_to_world(x, y, z, K, R, T, depth_scale=1000)
    return X, Y, Z

def get_table_world_coordinates():
    """
    Get table's world coordinate with camera extrinsics. X is towards to camera. Y is towards to right of the camera(facing the robot). Z is upward. 
    Note: Assume robot is in the middle of the table.
    return: (a, b, c, d) that corresponds to the left bottom, right bottom, left top, right top corner of the table.
    """
    left_bottom = [CAMERA_X-0.2, -TABLE_WIDTH/2, -ROBOT_TO_HEIGHT+CUBE_LENGTH]
    right_bottom = [CAMERA_X-0.2, TABLE_WIDTH/2, -ROBOT_TO_HEIGHT+CUBE_LENGTH]
    left_top = [ROBOT_BASE_LENGTH, -TABLE_WIDTH/2, -ROBOT_TO_HEIGHT+CUBE_LENGTH]
    right_top = [ROBOT_BASE_LENGTH, TABLE_WIDTH/2, -ROBOT_TO_HEIGHT+CUBE_LENGTH]
    # For some reason the ros and open3d have inverted x, y orientation. 
    # Also, the origin is at (0,0,0) instead of the robot base.
    # left_bottom = [-width/2, camera_x, height-robot_to_height]
    # right_bottom = [width/2, camera_x, height-robot_to_height]
    # left_top = [-width/2, -robot_to_width, height-robot_to_height]
    # right_top = [width/2, -robot_to_width, height-robot_to_height]
    return left_bottom, right_bottom, left_top, right_top

def world_to_image(point, K, R, T):
    """
    :param point: 3*1 array 
    :param K: 3*3 intrinsic matrix 
    :param R: 3*3 rotation matrix
    :param T: 3*1 translation matrix
    """
    # 3dpoint tmp = cameraintrinsic(3x3) * rotationvect(1x3) * xyz(3x1) + cameraintrinsic(3x3)*translation(3,1)
    # 2dpoint screen = tmp.x/tmp.z, tmp.y / tmp.z
    world_coord = K @ R @ point + K @ T
    return world_coord[0] / world_coord[2], world_coord[1] / world_coord[2]

def point_cloud_to_world(x, y, z, K, R, T, depth_scale=1000):
    """
    Transform (0,0,0) in point cloud back to world coordinates according to
    z = d / depth_scale = -X / depth_scale
    x = (u - cx) * z / fx
    y = (v - cy) * z / fy
    """
    fx, fy = K[0][0], K[1][1]
    cx, cy = K[0][2], K[1][2]
    d = z * depth_scale
    u = (x * fx) / z + cx
    v = y * fy / z + cy
    X, Y, Z = -d, u, v
    return X, Y, Z

def world_to_point_cloud(X, Y, Z, K, R, T, depth_scale=1000):  
    """
    World coordinate = (X, Y, Z). In world coordinate, d is in -X.
    u = 1/Z * [fx, 0, cz] @ R0 * X
    v = 1/Z * [0, fy, cy] @ R1 * Y
    Transform depth image to point cloud (in the image frame)
    z = d / depth_scale = -X / depth_scale
    x = (u - cx) * z / fx
    y = (v - cy) * z / fy
    """
    # u = 1/Z * (K[0] @ R[:, 0]) * X
    # v = 1/Z * (K[1] @ R[:, 1]) * Y
    u, v = world_to_image(np.array([[X], [Y], [Z]]), K, R, T)
    z = -X / depth_scale
    x = (u - K[0][1]) * z / K[0][0]
    y = (v - K[1][2]) * z / K[1][1]
    z = -X / depth_scale
    return x, y, z