from concurrent.futures import process
import copy
from tkinter import E
import numpy as np
import math
from PIL import Image
import matplotlib.pyplot as plt 
import imageio
from tqdm import tqdm
from PIL import Image
import glob
import cv2
import glob
import shutil
import os

def filter(real_img, sim_img):
    """
    Filter the simulated image from the real depth image.
    """
    masked_img = np.subtract(real_img, sim_img)
    return masked_img

def generate_depth_img_without_robot(depth_dir, mask_dir, filtered_depth_dir):
    """
    Filter out robot from depth image with the generated mask.
    :param str depth_dir: Directory to the original depth image from rosbag.
    :param str mask_dir: Directory to the mask generated by urdf_filter.
    :param str filtered_depth_dir: Directory to save the filtered depth image.
    """
    depth_img = np.loadtxt(depth_dir)
    # depth_img = Image.open(depth_dir)
    mask_img = Image.open(mask_dir)
    depth_array = np.array(depth_img)
    mask_array = np.array(mask_img)
    filtered_depth = copy.deepcopy(depth_array*1000)
    for i in range(mask_array.shape[0]):
        for j in range(mask_array.shape[1]):
            if mask_array[i][j] == 255:
                filtered_depth[i][j] = 0
    # plt.imshow(filtered_depth)
    # plt.colorbar()
    # plt.show()
    imageio.imwrite(filtered_depth_dir, filtered_depth.astype(np.uint16))
    return filtered_depth

def generate_rgb_image_without_robot(rgb_dir, mask_dir, filtered_rgb_dir):
    """
    Filter out robot from rgb image with the generated mask.
    :param str rgb_dir: Directory to the original rgb image from rosbag.
    :param str mask_dir: Directory to the mask generated by urdf_filter.
    :param str filtered_rgb_dir: Directory to save the filtered rgb image.
    """
    rgb_img = Image.open(rgb_dir)
    mask_img = Image.open(mask_dir)
    rgb_array = np.array(rgb_img)
    mask_array = np.array(mask_img)
    filtered_rgb = copy.deepcopy(rgb_array)
    for i in range(mask_array.shape[0]):
        for j in range(mask_array.shape[1]):
            if mask_array[i][j] == 255:
                filtered_rgb[i][j][0] = 0
                filtered_rgb[i][j][1] = 0
                filtered_rgb[i][j][2] = 0
    # plt.imshow(filtered_rgb)
    # plt.show()
    imageio.imwrite(filtered_rgb_dir, filtered_rgb)
    return filtered_rgb

def import_data(img_file, position_file, velocity_file):
    """
    Load data generated from rosbag.
    """
    # images = np.loadtxt(img_file) #importing images is very slow
    positions = np.loadtxt(position_file)
    velocities = np.loadtxt(velocity_file)
    print("position and velocities imported!")
    return positions, velocities

def write_real_depth_as_txt(start_frame, end_frame):
    """
    Save real depth txt at once since image I/O is very slow. 
    """
    img_dir = "./depth_data/images.txt" #depth image in the form of txt
    loaded_arr = np.loadtxt(img_dir)
    load_original_arr = loaded_arr.reshape(
    loaded_arr.shape[0], loaded_arr.shape[1] // 640, 640)
    print("Done loading images.")
    for frame_id in tqdm(range(start_frame, end_frame)):
        real_depth_dir = "./depth_data/real_depth_frame00000{}.txt".format(frame_id)
        print("frame_id", frame_id)
        real = load_original_arr[frame_id]
        np.savetxt(real_depth_dir, real)

def denoise(frame_id):
    """
    Filter out small pieces of noise from depth images. 
    """
    img_dir = "./cube_data/depth_image_frame00000{}.png".format(frame_id)
    denoise_mask_dir = "./denoise_cube_data/frame00000{}.png".format(frame_id)

    # Load image, convert to grayscale, Gaussian blur, Otsu's threshold
    image = cv2.imread(img_dir)
    gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
    blur = cv2.GaussianBlur(gray, (3,3), 0)
    thresh = cv2.threshold(blur, 0, 255, cv2.THRESH_BINARY_INV + cv2.THRESH_OTSU)[1]

    # Filter using contour area and remove small noise
    cnts = cv2.findContours(thresh, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)
    cnts = cnts[0] if len(cnts) == 2 else cnts[1]
    for c in cnts:
        area = cv2.contourArea(c)
        if area < 50:
            cv2.drawContours(thresh, [c], -1, (0,0,0), -1)

    # Morph close and invert image
    kernel = cv2.getStructuringElement(cv2.MORPH_RECT, (8,8))
    close = 255 - cv2.morphologyEx(thresh, cv2.MORPH_CLOSE, kernel, iterations=2)

    # cv2.imshow('thresh', thresh)
    # cv2.imshow('close', close)
    # cv2.waitKey()
    # cv2.destroyAllWindows()
    im = Image.fromarray(close)
    if im.mode != 'L':
        im = im.convert('L')
    im.save(denoise_mask_dir)

def axis_angle_to_rotation_matrix(axis, theta):
    """
    Return the rotation matrix associated with counterclockwise rotation about
    the given axis by theta radians.
    """
    axis = np.asarray(axis)
    axis = axis / math.sqrt(np.dot(axis, axis))
    a = math.cos(theta / 2.0)
    b, c, d = -axis * math.sin(theta / 2.0)
    aa, bb, cc, dd = a * a, b * b, c * c, d * d
    bc, ad, ac, ab, bd, cd = b * c, a * d, a * c, a * b, b * d, c * d
    return np.array([[aa + bb - cc - dd, 2 * (bc + ad), 2 * (bd - ac)],
                     [2 * (bc - ad), aa + cc - bb - dd, 2 * (cd + ab)],
                     [2 * (bd + ac), 2 * (cd - ab), aa + dd - bb - cc]])

def rotation_matrix_to_euler(R):
    beta = -np.arcsin(R[2,0])
    alpha = np.arctan2(R[2,1]/np.cos(beta),R[2,2]/np.cos(beta))
    gamma = np.arctan2(R[1,0]/np.cos(beta),R[0,0]/np.cos(beta))
    return np.array((alpha, beta, gamma))

def quaternion_rotation_matrix(Q):
    """
    Covert a quaternion into a full three-dimensional rotation matrix.
 
    Input
    :param Q: A 4 element array representing the quaternion (q0,q1,q2,q3) 
 
    Output
    :return: A 3x3 element matrix representing the full 3D rotation matrix. 
             This rotation matrix converts a point in the local reference 
             frame to a point in the global reference frame.
    """
    # Extract the values from Q
    q0 = Q[0]
    q1 = Q[1]
    q2 = Q[2]
    q3 = Q[3]
     
    # First row of the rotation matrix
    r00 = 2 * (q0 * q0 + q1 * q1) - 1
    r01 = 2 * (q1 * q2 - q0 * q3)
    r02 = 2 * (q1 * q3 + q0 * q2)
     
    # Second row of the rotation matrix
    r10 = 2 * (q1 * q2 + q0 * q3)
    r11 = 2 * (q0 * q0 + q2 * q2) - 1
    r12 = 2 * (q2 * q3 - q0 * q1)
     
    # Third row of the rotation matrix
    r20 = 2 * (q1 * q3 - q0 * q2)
    r21 = 2 * (q2 * q3 + q0 * q1)
    r22 = 2 * (q0 * q0 + q3 * q3) - 1
     
    # 3x3 rotation matrix
    rot_matrix = np.array([[r00, r01, r02],
                           [r10, r11, r12],
                           [r20, r21, r22]])   
    return rot_matrix

def world_to_image(point, K, R, T):
    """
    :param point: 3*1 array 
    :param K: 3*3 intrinsic matrix 
    :param R: 3*3 rotation matrix
    :param T: 3*1 translation matrix
    """
    world_coord = K @ R @ point + K @ T
    return world_coord[0] / world_coord[2], world_coord[1] / world_coord[2]

def world_to_point_cloud(X, Y, Z, K, R, T, depth_scale=1000):  
    """
    World coordinate = (X, Y, Z). In world coordinate, d is in -X.
    u = 1/Z * [fx, 0, cz] @ R0 * X
    v = 1/Z * [0, fy, cy] @ R1 * Y
    Transform depth image to point cloud (in the image frame)
    z = d / depth_scale = -X / depth_scale
    x = (u - cx) * z / fx
    y = (v - cy) * z / fy
    """
    # u = 1/Z * (K[0] @ R[:, 0]) * X
    # v = 1/Z * (K[1] @ R[:, 1]) * Y
    u, v = world_to_image(np.array([[X], [Y], [Z]]), K, R, T)
    z = -X / depth_scale
    x = (u - K[0][1]) * z / K[0][0]
    y = (v - K[1][2]) * z / K[1][1]
    z = -X / depth_scale
    return x, y, z

def render_gif():
    """
    Make pngs into a gif.
    """
    frames = []
    for frame_id in range(1, 4432):
        name = "./cube_data/screen_image_frame00000{}.png".format(frame_id)
        new_frame = Image.open(name)
        frames.append(new_frame)
    # Save into a GIF file that loops forever
    frames[0].save('./png_to_gif.gif', format='GIF',
                append_images=frames[1:],
                save_all=True,
                duration=300, loop=0)

def render_video():
    """
    Make pngs into a video for easy view.
    """
    fileList = []
    for frame_id in tqdm(range(1, 4432)):
        # filename = "./cube_data/screen_image_frame00000{}.png".format(frame_id)
        filename = "./denoise_cube_data/frame00000{}.png".format(frame_id)
        fileList.append(filename)

    writer = imageio.get_writer('new_depth.mp4', fps=20)

    for im in fileList:
        writer.append_data(imageio.imread(im))
    writer.close()

"""
Data preparation for running BundleTrack on our own RGBD data. 
"""
def copy():
    """
    For copying images from robot_filter folder to BundleTrack folder.
    """
    src_dir = "/home/cnets-vision/mengti_ws/robot_filter/depth_data"
    dst_dir = "/home/cnets-vision/mengti_ws/BundleTrack/Data/YCBINEOAT/contact_nets/depth"
    for jpgfile in glob.iglob(os.path.join(src_dir, "*.png")):
        shutil.copy(jpgfile, dst_dir)

def create_annotated_poses(output_dir, start_frame, end_frame):
    """
    Create annotated_poses folder. First txt is the transformation matrix from camera to object. 
    Others are identity matrices solely for evaluation.
    """
    if start_frame == 0: start_frame+=1
    for frame_id in range(start_frame, end_frame):
        filename = os.path.join(output_dir, "%04i.txt" % frame_id)
        pose = np.array([[1,0,0,0],[0,1,0,0],[0,0,1,0],[0,0,0,1]])
        np.savetxt(filename, pose)

def rename():
    """
    Currently, all data are named as frame00000{frame_id}.png. Need to rename to {frame_id}.png 
    to match the required format of BundleTrack.
    Go to the directory and run rename().
    """
    for filename in os.listdir("."):
        print(filename)
        if filename.startswith("frame"):
            os.rename(filename, filename[-8:])


def main():
    for frame_id in tqdm(range(1, 4432)):
    #     real_depth_file = "./depth_data/real_depth_frame00000{}.txt".format(frame_id)
    #     mask_image_file = "./mask_data/mask_frame00000{}.png".format(frame_id)
    #     filtered_depth_file = "./filtered_data/depth_without_robot_frame00000{}.png".format(frame_id)
    #     generate_depth_img_without_robot(real_depth_file, mask_image_file, filtered_depth_file)
    #     rgb_image_file = "./rgb_data/frame%06i.png" % frame_id
    #     filtered_rgb_file = "./filtered_data/rgb_without_robot_frame00000{}.png".format(frame_id)
    #     generate_rgb_image_without_robot(rgb_image_file, mask_image_file, filtered_rgb_file)
        real_depth_file = "./depth_data/real_depth_frame00000{}.txt".format(frame_id)
        mask_image_file = "./dilated_mask_data/frame00000{}.png".format(frame_id)
        filtered_depth_file = "./filtered_data/depth_without_robot_frame00000{}.png".format(frame_id)
        generate_depth_img_without_robot(real_depth_file, mask_image_file, filtered_depth_file)
        rgb_image_file = "./rgb_data/frame%06i.png" % frame_id
        filtered_rgb_file = "./filtered_data/rgb_without_robot_frame00000{}.png".format(frame_id)
        generate_rgb_image_without_robot(rgb_image_file, mask_image_file, filtered_rgb_file)

if __name__ == "__main__":
    # main()
    # render_video()
    # for frame_id in tqdm(range(1, 4432)):
        # denoise(frame_id)
    # denoise(774)
    # create_annotated_poses("/home/cnets-vision/mengti_ws/BundleTrack/Data/YCBINEOAT/contact_nets/annotated_poses", 1, 4432)
    rename()