dataset:
  cube: 10
  bottle: 43
  napkin: 53 #51
  box: 57
tosses:
  cube: #raw_10
    - toss: 1
      start_time:
        secs: 1655404893
        nsecs: 899137
      end_time:
        secs: 1655404908
        nsecs: 279948
      start_frame: 366
      end_frame: 384

    - toss: 2
      start_time:
        secs: 1655404908
        nsecs: 279948
      end_time:
        secs: 1655404920
        nsecs: 470680
      start_frame: 284
      end_frame: 308

    - toss: 3
      start_time:
        secs: 1655404920
        nsecs: 470680
      end_time:
        secs: 1655404932
        nsecs: 647236
      start_frame: 278
      end_frame: 300

    - toss: 4
      start_time:
        secs: 1655404932
        nsecs: 647236
      end_time:
        secs: 1655404945
        nsecs: 387903
      start_frame: 336
      end_frame: 358

    - toss: 5
      start_time:
        secs: 1655404945
        nsecs: 387903
      end_time:
        secs: 1655404955
        nsecs: 463919
      start_frame: 193
      end_frame: 214

    - toss: 6
      start_time:
        secs: 1655404955
        nsecs: 463919
      end_time:
        secs: 1655404968
        nsecs: 399762
      start_frame: 328
      end_frame: 348

    - toss: 7
      start_time:
        secs: 1655404968
        nsecs: 399762
      end_time:
        secs: 1655404978
        nsecs: 579412
      start_frame: 266
      end_frame: 284

    - toss: 8
      start_time:
        secs: 1655404978
        nsecs: 579412
      end_time:
        secs: 1655404992
        nsecs: 115224
      start_frame: 378
      end_frame: 398

    - toss: 9
      start_time:
        secs: 1655404992
        nsecs: 115224
      end_time:
        secs: 1655405008
        nsecs: 637576
      start_frame: 466
      end_frame: 481

    - toss: 10
      start_time:
        secs: 1655405008
        nsecs: 637576
      end_time:
        secs: 1655405023
        nsecs: 293250
      start_frame: 407
      end_frame: 430
    
    - toss: 11
      start_time:
        secs: 1655404893
        nsecs: 899137
      end_time:
        secs: 1655405023
        nsecs: 293250
      start_frame: 0
      end_frame: 0

  bottle: #raw_43
    - toss: 0
      start_time: 
        secs: 1691457459
        nsecs: 193690
      end_time:
        secs: 1691457518
        nsecs: 436350

    - toss: 1
      start_time:
        secs: 1691457459
        nsecs: 193690
      end_time:
        secs: 1691457462
        nsecs: 859556
      start_frame: 8
      end_frame: 75

    - toss: 2
      start_time:
        secs: 1691457463
        nsecs: 858847
      end_time:
        secs: 1691457467
        nsecs: 891929
      start_frame: 30
      end_frame: 115

    - toss: 3
      start_time:
        secs: 1691457469
        nsecs: 188822
      end_time:
        secs: 1691457475
        nsecs: 286966
      start_frame: 1
      end_frame: 170

    - toss: 4
      start_time:
        secs: 1691457477
        nsecs: 855128
      end_time:
        secs: 1691457481
        nsecs: 285988
      start_frame: 22
      end_frame: 110

    - toss: 5
      start_time:
        secs: 1691457483
        nsecs: 288794
      end_time:
        secs: 1691457485
        nsecs: 982220
      start_frame: 7
      end_frame: 60

    - toss: 6
      start_time:
        secs: 1691457487
        nsecs: 746206
      end_time:
        secs: 1691457490
        nsecs: 325132
      start_frame: 30
      end_frame: 85

    - toss: 7
      start_time:
        secs: 1691457491
        nsecs: 992030
      end_time:
        secs: 1691457495
        nsecs: 494258
      start_frame: 40
      end_frame: 112

    - toss: 8
      start_time:
        secs: 1691457496
        nsecs: 809137
      end_time:
        secs: 1691457505
        nsecs: 705429
      start_frame: 28
      end_frame: 250

    - toss: 9
      start_time:
        secs: 1691457507
        nsecs: 337440
      end_time:
        secs: 1691457513
        nsecs: 538905
      start_frame: 10
      end_frame: 175

    - toss: 10
      start_time:
        secs: 1691457515
        nsecs: 771419
      end_time:
        secs: 1691457518
        nsecs: 436350
      start_frame: 28
      end_frame: 85

  # cube_new:
  #   - toss: 1
  #     start_time:
  #       secs: 1667330354
  #       nsecs: 923693
  #     end_time:
  #       secs: 1667330357
  #       nsecs: 447548
  #     start_frame: 0
  #     end_frame: 0
  cube_new: #60 fps cude hand toss
    - toss: 1
      start_time:
        secs: 1695415477
        nsecs: 395064
      end_time:
        secs: 1695415479
        nsecs: 169873

  napkin: #raw_51
    - toss: 0 #entire dataset
      start_time:
        secs: 1696015383
        nsecs: 177608
      end_time:
        secs: 1696015425
        nsecs: 939109
  
    - toss: 1
      start_time:
        secs: 1696015383
        nsecs: 177608
      end_time:
        secs: 1696015386
        nsecs: 502336
      start_frame: 62
      end_frame: 90

    - toss: 2
      start_time:
        secs: 1696015386
        nsecs: 945471
      end_time:
        secs: 1696015390
        nsecs: 100687
      start_frame: 75
      end_frame: 100
      
    - toss: 3
      start_time:
        secs: 1696015391
        nsecs: 914609
      end_time:
        secs: 1696015393
        nsecs: 734324
      start_frame: 30
      end_frame: 55

    - toss: 4
      start_time:
        secs: 1696015395
        nsecs: 998295
      end_time:
        secs: 1696015397
        nsecs: 853870
      start_frame: 25
      end_frame: 50

    - toss: 5
      start_time:
        secs: 1696015399
        nsecs: 762283
      end_time:
        secs: 1696015401
        nsecs: 318823
      start_frame: 25
      end_frame: 55
    
    - toss: 6
      start_time:
        secs: 1696015403
        nsecs: 959935
      end_time:
        secs: 1696015405
        nsecs: 559247
      start_frame: 28
      end_frame: 48
    
    - toss: 7
      start_time:
        secs: 1696015408
        nsecs: 459369
      end_time:
        secs: 1696015410
        nsecs: 390742
      start_frame: 15
      end_frame: 45
    
    - toss: 8
      start_time:
        secs: 1696015412
        nsecs: 457875
      end_time:
        secs: 1696015414
        nsecs: 129579
      start_frame: 15
      end_frame: 60
    
    - toss: 9
      start_time:
        secs: 1696015416
        nsecs: 859006
      end_time:
        secs: 1696015421
        nsecs: 425617
      start_frame: 26
      end_frame: 140

    - toss: 10
      start_time:
        secs: 1696015423
        nsecs: 883122
      end_time:
        secs: 1696015425
        nsecs: 939109
      start_frame: 25
      end_frame: 55
    
    - toss: 11 #raw_53
      start_time:
        secs: 1696015461
        nsecs: 377774
      end_time:
        secs: 1696015463
        nsecs: 297168
      start_frame: 18
      end_frame: 40

    - toss: 12
      start_time:
        secs: 1696015465
        nsecs: 180744
      end_time:
        secs: 1696015466
        nsecs: 513879
      start_frame: 3
      end_frame: 25

    - toss: 13
      start_time:
        secs: 1696015468
        nsecs: 913827
      end_time:
        secs: 1696015470
        nsecs: 926227
      start_frame: 33
      end_frame: 55

  box: #raw_57
    - toss: 0
      start_time:
        secs: 1696622350
        nsecs: 960829
      end_time:
        secs: 1696622383
        nsecs: 653126
      start_frame: 0
      end_frame: 0
    - toss: 1
      start_time:
        secs: 1696622350
        nsecs: 960829
      end_time:
        secs: 1696622353
        nsecs: 123324
      start_frame: 91
      end_frame: 135
    - toss: 2
      start_time:
        secs: 1696622353
        nsecs: 123325
      end_time:
        secs: 1696622355
        nsecs: 722905
      start_frame: 78
      end_frame: 112
    - toss: 3
      start_time:
        secs: 1696622356
        nsecs: 224615
      end_time:
        secs: 1696622359
        nsecs: 276906
      start_frame: 100
      end_frame: 150
    - toss: 4
      start_time:
        secs: 1696622359
        nsecs: 612294
      end_time:
        secs: 1696622362
        nsecs: 510733
      start_frame: 120
      end_frame: 150
    - toss: 5
      start_time:
        secs: 1696622362
        nsecs: 614546
      end_time:
        secs: 1696622365
        nsecs: 363410
      start_frame: 
      end_frame: 
    - toss: 6
      start_time:
        secs: 1696622365
        nsecs: 619843
      end_time:
        secs: 1696622368
        nsecs: 616890
      start_frame: 
      end_frame: 
    - toss: 7
      start_time:
        secs: 1696622368
        nsecs: 900376
      end_time:
        secs: 1696622372
        nsecs: 256774
      start_frame: 
      end_frame: 
    - toss: 8
      start_time:
        secs: 1696622372
        nsecs: 437978
      end_time:
        secs: 1696622375
        nsecs: 623855
      start_frame: 
      end_frame: 
    - toss: 9
      start_time:
        secs: 1696622375
        nsecs: 789469
      end_time:
        secs: 1696622379
        nsecs: 462270
      start_frame: 
      end_frame: 
    - toss: 10
      start_time:
        secs: 1696622379
        nsecs: 850120
      end_time:
        secs: 1696622383
        nsecs: 653126
      start_frame: 
      end_frame: 
  
  half: #raw_59
    - toss: 0
      start_time:
        secs: 1698698660
        nsecs: 956753
      end_time:
        secs: 1698698696
        nsecs: 661494
    - toss: 1
      start_time:
        secs: 1698698660
        nsecs: 956753
      end_time:
        secs: 1698698663
        nsecs: 390371
      start_frame: None 
      end_frame: None
    - toss: 2
      start_time:
        secs: 1698698663
        nsecs: 390371
      end_time:
        secs: 1698698666
        nsecs: 743476
    - toss: 3
      start_time:
        secs: 1698698666
        nsecs: 743476
      end_time:
        secs: 1698698670
        nsecs: 549387
    - toss: 4
      start_time:
        secs: 1698698670
        nsecs: 549387
      end_time:
        secs: 1698698675
        nsecs: 194417
    - toss: 5
      start_time:
        secs: 1698698675
        nsecs: 194417
      end_time:
        secs: 1698698678
        nsecs: 104747
    - toss: 6
      start_time:
        secs: 1698698678
        nsecs: 104747
      end_time:
        secs: 1698698682
        nsecs: 534742
    - toss: 7
      start_time:
        secs: 1698698682
        nsecs: 534742
      end_time:
        secs: 1698698686
        nsecs: 135603
    - toss: 8
      start_time:
        secs: 1698698686
        nsecs: 135603
      end_time:
        secs: 1698698690
        nsecs: 195832
    - toss: 9
      start_time:
        secs: 1698698690
        nsecs: 195832
      end_time:
        secs: 1698698693
        nsecs: 271836
    - toss: 10
      start_time:
        secs: 1698698693
        nsecs: 271836
      end_time:
        secs: 1698698696
        nsecs: 661494

  toblerone:
    - toss: 0
      start_time:
        secs: 1698702014
        nsecs: 497514
      end_time:
        secs: 1698702047
        nsecs: 748595
    - toss: 1
      start_time:
        secs: 1698702014
        nsecs: 497514
      end_time:
        secs: 1698702016
        nsecs: 531097
    - toss: 2
      start_time:
        secs: 1698702016
        nsecs: 531097
      end_time:
        secs: 1698702019
        nsecs: 378815
    - toss: 3
      start_time:
        secs: 1698702019
        nsecs: 378815
      end_time:
        secs: 1698702022
        nsecs: 293393
    - toss: 4
      start_time:
        secs: 1698702022
        nsecs: 293393
      end_time:
        secs: 1698702025
        nsecs: 758027
    - toss: 5
      start_time:
        secs: 1698702025
        nsecs: 758027
      end_time:
        secs: 1698702029
        nsecs: 292161
    - toss: 6
      start_time:
        secs: 1698702029
        nsecs: 292161
      end_time:
        secs: 1698702033
        nsecs: 218646
    - toss: 7
      start_time:
        secs: 1698702033
        nsecs: 218646 
      end_time:
        secs: 1698702036
        nsecs: 555118
    - toss: 8
      start_time:
        secs: 1698702036
        nsecs: 555118
      end_time:
        secs: 1698702040
        nsecs: 700482
    - toss: 9
      start_time:
        secs: 1698702040
        nsecs: 700482
      end_time:
        secs: 1698702044
        nsecs: 257065
    - toss: 10
      start_time:
        secs: 1698702044
        nsecs: 257065
      end_time:
        secs: 1698702047
        nsecs: 748595